In [1]:
!pip install selenium
import time
import warnings
warnings.filterwarnings('ignore')

Requirement already satisfied: selenium in c:\users\srividya\anaconda3\lib\site-packages (4.0.0b4)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: urllib3[secure]~=1.26 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (1.26.4)
Requirement already satisfied: trio~=0.17 in c:\users\srividya\anaconda3\lib\site-packages (from selenium) (0.19.0)
Requirement already satisfied: cffi>=1.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.14.5)
Requirement already satisfied: async-generator>=1.9 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: attrs>=19.2.0 in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (20.3.0)
Requirement already satisfied: idna in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.10)
Requirement already satisfied: sniffio in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: sortedcontainers in c:\users\srividya\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.3.0)
Requirement already satisfied: pycparser in c:\users\srividya\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.20)
Requirement already satisfied: wsproto>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.0.0)
Requirement already satisfied: cryptography>=1.3.4 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (3.4.7)
Requirement already satisfied: pyOpenSSL>=0.14 in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (20.0.1)
Requirement already satisfied: certifi in c:\users\srividya\anaconda3\lib\site-packages (from urllib3[secure]~=1.26->selenium) (2020.12.5)
Requirement already satisfied: six>=1.5.2 in c:\users\srividya\anaconda3\lib\site-packages (from pyOpenSSL>=0.14->urllib3[secure]~=1.26->selenium) (1.15.0)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\srividya\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.12.0)

In [2]:
import selenium
import pandas as pd
from selenium import webdriver

In [3]:
driver=webdriver.Chrome(r"C:\Users\Srividya\Downloads\chromedriver_win32\chromedriver.exe")

In [4]:
url="https://www.forbes.com/?sh=24d973e72254"
driver.get(url)

In [5]:

from selenium.common.exceptions import  StaleElementReferenceException,ElementClickInterceptedException
from selenium.common.exceptions import  NoSuchElementException,NoSuchWindowException

from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

In [6]:
menu=driver.find_element_by_xpath("//button[@class='icon--hamburger']")
menu.click()

In [7]:
menu_bi=driver.find_element_by_xpath("//li[@class='header__channel header__color--centennial-silver header__hoverable']")

In [8]:
from selenium.webdriver.common.action_chains import ActionChains

In [9]:
element_to_hover_over = driver.find_element_by_xpath("//li[@class='header__channel header__color--centennial-silver header__hoverable']")
ActionChains(driver).move_to_element(element_to_hover_over).perform()

In [10]:
menu_bi1=driver.find_element_by_xpath("//ul[@class='header__sections header__color--centennial-silver']//li[2]//a")

In [11]:
element_to_hover_over1 = driver.find_element_by_xpath("//li[@class='header__channel header__color--centennial-silver header__hoverable']")
ActionChains(driver).move_to_element(element_to_hover_over1).perform()
menu_bi1.click()

In [12]:
rank1=[]
for page in range(0,13):
    rankk=driver.find_elements_by_xpath("//div[@class='rank']")
    for i in rankk:
        rank1.append(i.text)
    nxt_button=driver.find_element_by_xpath("//div[@class='pagination']//button[2]//div//i")
    try:
        nxt_button.click()  
    except:
        time.sleep(1)

In [13]:
rank1

['1.',
 '2.',
 '3.',
 '4.',
 '5.',
 '6.',
 '7.',
 '8.',
 '9.',
 '10.',
 '11.',
 '12.',
 '13.',
 '14.',
 '15.',
 '16.',
 '17.',
 '18.',
 '19.',
 '20.',
 '21.',
 '22.',
 '23.',
 '24.',
 '25.',
 '26.',
 '27.',
 '27.',
 '29.',
 '30.',
 '31.',
 '32.',
 '33.',
 '34.',
 '35.',
 '36.',
 '37.',
 '38.',
 '39.',
 '40.',
 '41.',
 '41.',
 '43.',
 '44.',
 '45.',
 '46.',
 '47.',
 '48.',
 '48.',
 '50.',
 '51.',
 '52.',
 '53.',
 '53.',
 '55.',
 '56.',
 '57.',
 '58.',
 '59.',
 '60.',
 '61.',
 '62.',
 '62.',
 '64.',
 '65.',
 '66.',
 '66.',
 '68.',
 '69.',
 '70.',
 '71.',
 '71.',
 '73.',
 '74.',
 '75.',
 '75.',
 '77.',
 '78.',
 '79.',
 '80.',
 '81.',
 '82.',
 '83.',
 '84.',
 '85.',
 '86.',
 '87.',
 '88.',
 '89.',
 '89.',
 '89.',
 '92.',
 '93.',
 '94.',
 '95.',
 '96.',
 '96.',
 '98.',
 '99.',
 '100.',
 '100.',
 '102.',
 '103.',
 '104.',
 '105.',
 '105.',
 '107.',
 '107.',
 '109.',
 '110.',
 '111.',
 '112.',
 '113.',
 '114.',
 '115.',
 '116.',
 '117.',
 '118.',
 '119.',
 '119.',
 '121.',
 '121.',
 '121.',
 '124.',
 '124.',
 '126.',
 '127.',
 '128.',
 '128.',
 '128.',
 '131.',
 '132.',
 '133.',
 '133.',
 '133.',
 '133.',
 '137.',
 '138.',
 '138.',
 '140.',
 '140.',
 '142.',
 '142.',
 '144.',
 '145.',
 '145.',
 '145.',
 '148.',
 '148.',
 '150.',
 '151.',
 '151.',
 '151.',
 '154.',
 '155.',
 '156.',
 '156.',
 '158.',
 '158.',
 '158.',
 '161.',
 '161.',
 '163.',
 '164.',
 '164.',
 '166.',
 '166.',
 '168.',
 '169.',
 '169.',
 '171.',
 '171.',
 '173.',
 '173.',
 '173.',
 '173.',
 '177.',
 '177.',
 '177.',
 '177.',
 '181.',
 '182.',
 '182.',
 '184.',
 '185.',
 '186.',
 '186.',
 '186.',
 '189.',
 '189.',
 '191.',
 '191.',
 '193.',
 '194.',
 '195.',
 '195.',
 '197.',
 '197.',
 '197.',
 '200.',
 '200.',
 '200.',
 '203.',
 '203.',
 '205.',
 '205.',
 '205.',
 '208.',
 '208.',
 '210.',
 '210.',
 '210.',
 '213.',
 '213.',
 '213.',
 '216.',
 '216.',
 '216.',
 '219.',
 '219.',
 '219.',
 '219.',
 '223.',
 '224.',
 '224.',
 '224.',
 '224.',
 '228.',
 '228.',
 '230.',
 '230.',
 '232.',
 '232.',
 '234.',
 '234.',
 '234.',
 '234.',
 '234.',
 '234.',
 '234.',
 '241.',
 '241.',
 '241.',
 '241.',
 '245.',
 '245.',
 '247.',
 '247.',
 '247.',
 '247.',
 '251.',
 '251.',
 '251.',
 '251.',
 '255.',
 '256.',
 '256.',
 '256.',
 '256.',
 '256.',
 '256.',
 '262.',
 '262.',
 '264.',
 '264.',
 '264.',
 '264.',
 '264.',
 '269.',
 '269.',
 '269.',
 '269.',
 '269.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '274.',
 '288.',
 '288.',
 '288.',
 '288.',
 '288.',
 '288.',
 '294.',
 '294.',
 '294.',
 '297.',
 '297.',
 '297.',
 '297.',
 '297.',
 '297.',
 '297.',
 '304.',
 '304.',
 '304.',
 '304.',
 '308.',
 '308.',
 '308.',
 '311.',
 '311.',
 '311.',
 '311.',
 '311.',
 '316.',
 '316.',
 '316.',
 '316.',
 '316.',
 '316.',
 '316.',
 '323.',
 '323.',
 '323.',
 '323.',
 '327.',
 '327.',
 '327.',
 '327.',
 '327.',
 '327.',
 '327.',
 '334.',
 '334.',
 '334.',
 '334.',
 '334.',
 '339.',
 '339.',
 '339.',
 '339.',
 '339.',
 '344.',
 '344.',
 '344.',
 '344.',
 '344.',
 '344.',
 '344.',
 '344.',
 '352.',
 '352.',
 '352.',
 '352.',
 '352.',
 '352.',
 '358.',
 '358.',
 '358.',
 '358.',
 '358.',
 '358.',
 '358.',
 '358.',
 '358.',
 '358.',
 '358.',
 '369.',
 '369.',
 '369.',
 '369.',
 '369.',
 '369.',
 '369.',
 '369.',
 '369.',
 '369.',
 '369.',
 '380.',
 '380.',
 '380.',
 '380.',
 '384.',
 '384.',
 '384.',
 '384.',
 '384.',
 '384.',
 '384.',
 '391.',
 '391.',
 '391.',
 '391.',
 '391.',
 '391.',
 '391.',
 '391.',
 '391.',
 '400.',
 '400.',
 '400.',
 '400.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '404.',
 '418.',
 '418.',
 '418.',
 '421.',
 '421.',
 '421.',
 '421.',
 '421.',
 '421.',
 '421.',
 '421.',
 '421.',
 '421.',
 '421.',
 '432.',
 '432.',
 '432.',
 '432.',
 '432.',
 '432.',
 '432.',
 '432.',
 '440.',
 '440.',
 '440.',
 '440.',
 '440.',
 '440.',
 '440.',
 '440.',
 '440.',
 '440.',
 '440.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '451.',
 '472.',
 '472.',
 '472.',
 '472.',
 '476.',
 '476.',
 '476.',
 '476.',
 '476.',
 '476.',
 '476.',
 '476.',
 '476.',
 '476.',
 '486.',
 '486.',
 '486.',
 '486.',
 '486.',
 '486.',
 '486.',
 '486.',
 '486.',
 '486.',
 '496.',
 '496.',
 '496.',
 '496.',
 '496.',
 '496.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '502.',
 '520.',
 '520.',
 '520.',
 '520.',
 '520.',
 '520.',
 '520.',
 '520.',
 '520.',
 '529.',
 '529.',
 '529.',
 '529.',
 '529.',
 '529.',
 '529.',
 '529.',
 '529.',
 '529.',
 '539.',
 '539.',
 '539.',
 '539.',
 '539.',
 '539.',
 '539.',
 '539.',
 '539.',
 '539.',
 '539.',
 '550.',
 '550.',
 '550.',
 '550.',
 '550.',
 '550.',
 '550.',
 '550.',
 '550.',
 '550.',
 '550.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '561.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '574.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '589.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '608.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '622.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '638.',
 '655.',
 '655.',
 '655.',
 '655.',
 '655.',
 '655.',
 '655.',
 '655.',
 '655.',
 '655.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '665.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '680.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '705.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '727.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '752.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '775.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '807.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '831.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '859.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '891.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '925.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '956.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 '986.',
 ...]

In [36]:
len(rank1)

2600

In [14]:
for i in range(0,13):
    prev_button=driver.find_element_by_xpath("//div[@class='pagination']//button[1]//div//i")
    try:
        prev_button.click()  
    except:
        time.sleep(1)

In [15]:
names=[]
for page in range(0,13):
    name=driver.find_elements_by_xpath("//div[@class='personName']")
    for i in name:
        names.append(i.text)
    nxt_button=driver.find_element_by_xpath("//div[@class='pagination']//button[2]//div//i")
    try:
        nxt_button.click()  
    except:
        time.sleep(1)

In [16]:
names

['Martha MacMillan',
 'William MacMillan',
 'Yasseen Mansour',
 'John Martin',
 'Carsten Maschmeyer',
 'Bruce Mathieson',
 'John McConnell & family',
 'Takanori Nakamura',
 'Bruce Nordstrom',
 'Madeleine Olsson Ericksson',
 'Ou Xueming',
 'Mats Paulsson & family',
 'Peng Hao',
 'Ricardo Po Sr. & family',
 'Forrest Preston',
 'Enrico Preziosi',
 'Pu Shulin',
 'Qiu Lingyun',
 'Vera Rechulski Santo Domingo',
 'M.Satyanarayana Reddy',
 'Ruan Hongxian & family',
 'Chanchai Ruayrungruang',
 'Daisuke Sasaki',
 'Jack Schuler',
 'Neerja Sethi',
 'Shin Dong-guk',
 'Edgar Sia II',
 'Michael S. Smith',
 'Su Rubo',
 'Sun Xishuang',
 'Sehat Sutardja',
 'Susanto Suwarto',
 'Tan Eng Kee',
 'Tan Yu Wei',
 'Yoshikazu Tanaka',
 'Hary Tanoesoedibjo',
 'Mehmet Sinan Tara',
 'Shirou Terashita',
 'Carl Thoma',
 'Tseng Sing-ai',
 'Sunil Vachani',
 'Jan Van Geet',
 'Sekar Vembu',
 'Wang Han',
 'Wang Jianliang',
 'Wang Kunxiao',
 'Wen Pengcheng & family',
 'Wen Yibo & family',
 'Anne Werninghaus',
 'Dan Wilks',
 'Wong Hei & family',
 'Wong Hong King',
 'Wu Chung-yi',
 'Wu Eddie Yongming',
 'Eugene Wu',
 'Wu Wei',
 'Xiao Guoqing',
 'George Yancopoulos',
 'Yao Lisheng',
 'Yu Faxiang',
 'Yuan Jinhua',
 'Igor Yusufov',
 'Zan Shengda',
 'Zeng Huansha',
 'Zhang Xuewu',
 'Zhang Yuxiang & family',
 'Zhao Tongtong',
 'Tony Zhao',
 'Zhong Peifeng',
 'Zhou Ping & family',
 'Zhou Yahui',
 'Boris Zingarevich',
 'Ahmet Nazif Zorlu',
 'A. Jayson Adair',
 'Albert Avdolyan',
 'Baiju Bhatt',
 "Wilbur 'Ed' Bosarge, Jr.",
 'Ina Chan',
 'Chang Byung-gyu',
 'Chung Mong-joon',
 'Carmen Daurella Aguilera',
 'GT Dave',
 'Mukand Lal Dua',
 'Ramesh Kumar Dua',
 'Jose Elias',
 'Larry Fink',
 'Horst-Otto Gerberding',
 'Gim Seong-gon',
 'Gou Yiqun',
 'Clelia Haji-Ioannou',
 'Hang Hong',
 'Ronnen Harary',
 'David Harding',
 'David Helgason',
 'Hou Jianbin',
 'Hur Young-in',
 'Jiang Long',
 'Morris Kahn',
 'Ashok Kajaria',
 'T.S. Kalyanaraman',
 'Kim Kardashian West',
 'David Katzman',
 'Bom Kim',
 'Masatoshi Kumagai',
 'Lev Kvetnoi',
 'Vladimir Leschikov',
 'Li Yinan',
 'Liu Qingfeng',
 'Jose Llado Fernandez-Urrutia',
 'Kenneth Lo',
 'Ma Hong',
 'Sergei Makhlai',
 'Rafique Malik',
 'Mao Huihua',
 'Michael McCain',
 'Mofatraj Munot',
 'Vitaly Orlov',
 'George Pedersen',
 'David Penaloza Alanis',
 'Tyler Perry',
 'Maria Pinheiro',
 'Anton Rabie',
 'Jorge Rodriguez Rodriguez',
 'Hartley Rogers',
 'Alan Rydge',
 'Shin Dong-joo',
 'Scott Smith',
 'Zakhar Smushkin',
 'Marco Squinzi',
 'Veronica Squinzi',
 'Axel Stawski',
 'Manny Stul',
 'Vlad Tenev',
 'Rit Thirakomen',
 'Tong Judy Wenhong',
 'Tsai Chi-jui',
 'Surin Upatkoon',
 'Ruben Vardanyan',
 'Murat Vargi',
 'Vlad Vendrow & family',
 'Wang Qiangxiang',
 'Wang Wenjian',
 'J. Wayne Weaver',
 'Sandy Weill',
 'Xia Zhisheng & family',
 'Xu Jin',
 'Vadim Yakunin',
 'Mark Haoyong Yang',
 'Yao Hsiao Tung',
 'Yu De-Chao',
 'Daniel Yong Zhang',
 'Zhang Yuqiang',
 'Zhao Meiguang',
 'Zhong Naixiong',
 'Zhou Wei family',
 'Martha MacMillan',
 'William MacMillan',
 'Yasseen Mansour',
 'John Martin',
 'Carsten Maschmeyer',
 'Bruce Mathieson',
 'John McConnell & family',
 'Takanori Nakamura',
 'Bruce Nordstrom',
 'Madeleine Olsson Ericksson',
 'Ou Xueming',
 'Mats Paulsson & family',
 'Peng Hao',
 'Ricardo Po Sr. & family',
 'Forrest Preston',
 'Enrico Preziosi',
 'Pu Shulin',
 'Qiu Lingyun',
 'Vera Rechulski Santo Domingo',
 'M.Satyanarayana Reddy',
 'Ruan Hongxian & family',
 'Chanchai Ruayrungruang',
 'Daisuke Sasaki',
 'Jack Schuler',
 'Neerja Sethi',
 'Shin Dong-guk',
 'Edgar Sia II',
 'Michael S. Smith',
 'Su Rubo',
 'Sun Xishuang',
 'Sehat Sutardja',
 'Susanto Suwarto',
 'Tan Eng Kee',
 'Tan Yu Wei',
 'Yoshikazu Tanaka',
 'Hary Tanoesoedibjo',
 'Mehmet Sinan Tara',
 'Shirou Terashita',
 'Carl Thoma',
 'Tseng Sing-ai',
 'Sunil Vachani',
 'Jan Van Geet',
 'Sekar Vembu',
 'Wang Han',
 'Wang Jianliang',
 'Wang Kunxiao',
 'Wen Pengcheng & family',
 'Wen Yibo & family',
 'Anne Werninghaus',
 'Dan Wilks',
 'Wong Hei & family',
 'Wong Hong King',
 'Wu Chung-yi',
 'Wu Eddie Yongming',
 'Eugene Wu',
 'Wu Wei',
 'Xiao Guoqing',
 'George Yancopoulos',
 'Yao Lisheng',
 'Yu Faxiang',
 'Yuan Jinhua',
 'Igor Yusufov',
 'Zan Shengda',
 'Zeng Huansha',
 'Zhang Xuewu',
 'Zhang Yuxiang & family',
 'Zhao Tongtong',
 'Tony Zhao',
 'Zhong Peifeng',
 'Zhou Ping & family',
 'Zhou Yahui',
 'Boris Zingarevich',
 'Ahmet Nazif Zorlu',
 'A. Jayson Adair',
 'Albert Avdolyan',
 'Baiju Bhatt',
 "Wilbur 'Ed' Bosarge, Jr.",
 'Ina Chan',
 'Chang Byung-gyu',
 'Chung Mong-joon',
 'Carmen Daurella Aguilera',
 'GT Dave',
 'Mukand Lal Dua',
 'Ramesh Kumar Dua',
 'Jose Elias',
 'Larry Fink',
 'Horst-Otto Gerberding',
 'Gim Seong-gon',
 'Gou Yiqun',
 'Clelia Haji-Ioannou',
 'Hang Hong',
 'Ronnen Harary',
 'David Harding',
 'David Helgason',
 'Hou Jianbin',
 'Hur Young-in',
 'Jiang Long',
 'Morris Kahn',
 'Ashok Kajaria',
 'T.S. Kalyanaraman',
 'Kim Kardashian West',
 'David Katzman',
 'Bom Kim',
 'Masatoshi Kumagai',
 'Lev Kvetnoi',
 'Vladimir Leschikov',
 'Li Yinan',
 'Liu Qingfeng',
 'Jose Llado Fernandez-Urrutia',
 'Kenneth Lo',
 'Ma Hong',
 'Sergei Makhlai',
 'Rafique Malik',
 'Mao Huihua',
 'Michael McCain',
 'Mofatraj Munot',
 'Vitaly Orlov',
 'George Pedersen',
 'David Penaloza Alanis',
 'Tyler Perry',
 'Maria Pinheiro',
 'Anton Rabie',
 'Jorge Rodriguez Rodriguez',
 'Hartley Rogers',
 'Alan Rydge',
 'Shin Dong-joo',
 'Scott Smith',
 'Zakhar Smushkin',
 'Marco Squinzi',
 'Veronica Squinzi',
 'Axel Stawski',
 'Manny Stul',
 'Vlad Tenev',
 'Rit Thirakomen',
 'Tong Judy Wenhong',
 'Tsai Chi-jui',
 'Surin Upatkoon',
 'Ruben Vardanyan',
 'Murat Vargi',
 'Vlad Vendrow & family',
 'Wang Qiangxiang',
 'Wang Wenjian',
 'J. Wayne Weaver',
 'Sandy Weill',
 'Xia Zhisheng & family',
 'Xu Jin',
 'Vadim Yakunin',
 'Mark Haoyong Yang',
 'Yao Hsiao Tung',
 'Yu De-Chao',
 'Daniel Yong Zhang',
 'Zhang Yuqiang',
 'Zhao Meiguang',
 'Zhong Naixiong',
 'Zhou Wei family',
 'Martha MacMillan',
 'William MacMillan',
 'Yasseen Mansour',
 'John Martin',
 'Carsten Maschmeyer',
 'Bruce Mathieson',
 'John McConnell & family',
 'Takanori Nakamura',
 'Bruce Nordstrom',
 'Madeleine Olsson Ericksson',
 'Ou Xueming',
 'Mats Paulsson & family',
 'Peng Hao',
 'Ricardo Po Sr. & family',
 'Forrest Preston',
 'Enrico Preziosi',
 'Pu Shulin',
 'Qiu Lingyun',
 'Vera Rechulski Santo Domingo',
 'M.Satyanarayana Reddy',
 'Ruan Hongxian & family',
 'Chanchai Ruayrungruang',
 'Daisuke Sasaki',
 'Jack Schuler',
 'Neerja Sethi',
 'Shin Dong-guk',
 'Edgar Sia II',
 'Michael S. Smith',
 'Su Rubo',
 'Sun Xishuang',
 'Sehat Sutardja',
 'Susanto Suwarto',
 'Tan Eng Kee',
 'Tan Yu Wei',
 'Yoshikazu Tanaka',
 'Hary Tanoesoedibjo',
 'Mehmet Sinan Tara',
 'Shirou Terashita',
 'Carl Thoma',
 'Tseng Sing-ai',
 'Sunil Vachani',
 'Jan Van Geet',
 'Sekar Vembu',
 'Wang Han',
 'Wang Jianliang',
 'Wang Kunxiao',
 'Wen Pengcheng & family',
 'Wen Yibo & family',
 'Anne Werninghaus',
 'Dan Wilks',
 'Wong Hei & family',
 'Wong Hong King',
 'Wu Chung-yi',
 'Wu Eddie Yongming',
 'Eugene Wu',
 'Wu Wei',
 'Xiao Guoqing',
 'George Yancopoulos',
 'Yao Lisheng',
 'Yu Faxiang',
 'Yuan Jinhua',
 'Igor Yusufov',
 'Zan Shengda',
 'Zeng Huansha',
 'Zhang Xuewu',
 'Zhang Yuxiang & family',
 'Zhao Tongtong',
 'Tony Zhao',
 'Zhong Peifeng',
 'Zhou Ping & family',
 'Zhou Yahui',
 'Boris Zingarevich',
 'Ahmet Nazif Zorlu',
 'A. Jayson Adair',
 'Albert Avdolyan',
 'Baiju Bhatt',
 "Wilbur 'Ed' Bosarge, Jr.",
 'Ina Chan',
 'Chang Byung-gyu',
 'Chung Mong-joon',
 'Carmen Daurella Aguilera',
 'GT Dave',
 'Mukand Lal Dua',
 'Ramesh Kumar Dua',
 'Jose Elias',
 'Larry Fink',
 'Horst-Otto Gerberding',
 'Gim Seong-gon',
 'Gou Yiqun',
 'Clelia Haji-Ioannou',
 'Hang Hong',
 'Ronnen Harary',
 'David Harding',
 'David Helgason',
 'Hou Jianbin',
 'Hur Young-in',
 'Jiang Long',
 'Morris Kahn',
 'Ashok Kajaria',
 'T.S. Kalyanaraman',
 'Kim Kardashian West',
 'David Katzman',
 'Bom Kim',
 'Masatoshi Kumagai',
 'Lev Kvetnoi',
 'Vladimir Leschikov',
 'Li Yinan',
 'Liu Qingfeng',
 'Jose Llado Fernandez-Urrutia',
 'Kenneth Lo',
 'Ma Hong',
 'Sergei Makhlai',
 'Rafique Malik',
 'Mao Huihua',
 'Michael McCain',
 'Mofatraj Munot',
 'Vitaly Orlov',
 'George Pedersen',
 'David Penaloza Alanis',
 'Tyler Perry',
 'Maria Pinheiro',
 'Anton Rabie',
 'Jorge Rodriguez Rodriguez',
 'Hartley Rogers',
 'Alan Rydge',
 'Shin Dong-joo',
 'Scott Smith',
 'Zakhar Smushkin',
 'Marco Squinzi',
 'Veronica Squinzi',
 'Axel Stawski',
 'Manny Stul',
 'Vlad Tenev',
 'Rit Thirakomen',
 'Tong Judy Wenhong',
 'Tsai Chi-jui',
 'Surin Upatkoon',
 'Ruben Vardanyan',
 'Murat Vargi',
 'Vlad Vendrow & family',
 'Wang Qiangxiang',
 'Wang Wenjian',
 'J. Wayne Weaver',
 'Sandy Weill',
 'Xia Zhisheng & family',
 'Xu Jin',
 'Vadim Yakunin',
 'Mark Haoyong Yang',
 'Yao Hsiao Tung',
 'Yu De-Chao',
 'Daniel Yong Zhang',
 'Zhang Yuqiang',
 'Zhao Meiguang',
 'Zhong Naixiong',
 'Zhou Wei family',
 'Martha MacMillan',
 'William MacMillan',
 'Yasseen Mansour',
 'John Martin',
 'Carsten Maschmeyer',
 'Bruce Mathieson',
 'John McConnell & family',
 'Takanori Nakamura',
 'Bruce Nordstrom',
 'Madeleine Olsson Ericksson',
 'Ou Xueming',
 'Mats Paulsson & family',
 'Peng Hao',
 'Ricardo Po Sr. & family',
 'Forrest Preston',
 'Enrico Preziosi',
 'Pu Shulin',
 'Qiu Lingyun',
 'Vera Rechulski Santo Domingo',
 'M.Satyanarayana Reddy',
 'Ruan Hongxian & family',
 'Chanchai Ruayrungruang',
 'Daisuke Sasaki',
 'Jack Schuler',
 'Neerja Sethi',
 'Shin Dong-guk',
 'Edgar Sia II',
 'Michael S. Smith',
 'Su Rubo',
 'Sun Xishuang',
 'Sehat Sutardja',
 'Susanto Suwarto',
 'Tan Eng Kee',
 'Tan Yu Wei',
 'Yoshikazu Tanaka',
 'Hary Tanoesoedibjo',
 'Mehmet Sinan Tara',
 'Shirou Terashita',
 'Carl Thoma',
 'Tseng Sing-ai',
 'Sunil Vachani',
 'Jan Van Geet',
 'Sekar Vembu',
 'Wang Han',
 'Wang Jianliang',
 'Wang Kunxiao',
 'Wen Pengcheng & family',
 'Wen Yibo & family',
 'Anne Werninghaus',
 'Dan Wilks',
 'Wong Hei & family',
 'Wong Hong King',
 'Wu Chung-yi',
 'Wu Eddie Yongming',
 'Eugene Wu',
 'Wu Wei',
 'Xiao Guoqing',
 'George Yancopoulos',
 'Yao Lisheng',
 'Yu Faxiang',
 'Yuan Jinhua',
 'Igor Yusufov',
 'Zan Shengda',
 'Zeng Huansha',
 'Zhang Xuewu',
 'Zhang Yuxiang & family',
 'Zhao Tongtong',
 'Tony Zhao',
 'Zhong Peifeng',
 'Zhou Ping & family',
 'Zhou Yahui',
 'Boris Zingarevich',
 'Ahmet Nazif Zorlu',
 'A. Jayson Adair',
 'Albert Avdolyan',
 'Baiju Bhatt',
 "Wilbur 'Ed' Bosarge, Jr.",
 'Ina Chan',
 'Chang Byung-gyu',
 'Chung Mong-joon',
 'Carmen Daurella Aguilera',
 'GT Dave',
 'Mukand Lal Dua',
 'Ramesh Kumar Dua',
 'Jose Elias',
 'Larry Fink',
 'Horst-Otto Gerberding',
 'Gim Seong-gon',
 'Gou Yiqun',
 'Clelia Haji-Ioannou',
 'Hang Hong',
 'Ronnen Harary',
 'David Harding',
 'David Helgason',
 'Hou Jianbin',
 'Hur Young-in',
 'Jiang Long',
 'Morris Kahn',
 'Ashok Kajaria',
 'T.S. Kalyanaraman',
 'Kim Kardashian West',
 'David Katzman',
 'Bom Kim',
 'Masatoshi Kumagai',
 'Lev Kvetnoi',
 'Vladimir Leschikov',
 'Li Yinan',
 'Liu Qingfeng',
 'Jose Llado Fernandez-Urrutia',
 'Kenneth Lo',
 'Ma Hong',
 'Sergei Makhlai',
 'Rafique Malik',
 'Mao Huihua',
 'Michael McCain',
 'Mofatraj Munot',
 'Vitaly Orlov',
 'George Pedersen',
 'David Penaloza Alanis',
 'Tyler Perry',
 'Maria Pinheiro',
 'Anton Rabie',
 'Jorge Rodriguez Rodriguez',
 'Hartley Rogers',
 'Alan Rydge',
 'Shin Dong-joo',
 'Scott Smith',
 'Zakhar Smushkin',
 'Marco Squinzi',
 'Veronica Squinzi',
 'Axel Stawski',
 'Manny Stul',
 'Vlad Tenev',
 'Rit Thirakomen',
 'Tong Judy Wenhong',
 'Tsai Chi-jui',
 'Surin Upatkoon',
 'Ruben Vardanyan',
 'Murat Vargi',
 'Vlad Vendrow & family',
 'Wang Qiangxiang',
 'Wang Wenjian',
 'J. Wayne Weaver',
 'Sandy Weill',
 'Xia Zhisheng & family',
 'Xu Jin',
 'Vadim Yakunin',
 'Mark Haoyong Yang',
 'Yao Hsiao Tung',
 'Yu De-Chao',
 'Daniel Yong Zhang',
 'Zhang Yuqiang',
 'Zhao Meiguang',
 'Zhong Naixiong',
 'Zhou Wei family',
 'Martha MacMillan',
 'William MacMillan',
 'Yasseen Mansour',
 'John Martin',
 'Carsten Maschmeyer',
 'Bruce Mathieson',
 'John McConnell & family',
 'Takanori Nakamura',
 'Bruce Nordstrom',
 'Madeleine Olsson Ericksson',
 'Ou Xueming',
 'Mats Paulsson & family',
 'Peng Hao',
 'Ricardo Po Sr. & family',
 'Forrest Preston',
 'Enrico Preziosi',
 'Pu Shulin',
 'Qiu Lingyun',
 'Vera Rechulski Santo Domingo',
 'M.Satyanarayana Reddy',
 'Ruan Hongxian & family',
 'Chanchai Ruayrungruang',
 'Daisuke Sasaki',
 'Jack Schuler',
 'Neerja Sethi',
 'Shin Dong-guk',
 'Edgar Sia II',
 'Michael S. Smith',
 'Su Rubo',
 'Sun Xishuang',
 'Sehat Sutardja',
 'Susanto Suwarto',
 'Tan Eng Kee',
 'Tan Yu Wei',
 'Yoshikazu Tanaka',
 'Hary Tanoesoedibjo',
 'Mehmet Sinan Tara',
 'Shirou Terashita',
 'Carl Thoma',
 'Tseng Sing-ai',
 'Sunil Vachani',
 'Jan Van Geet',
 'Sekar Vembu',
 'Wang Han',
 'Wang Jianliang',
 'Wang Kunxiao',
 'Wen Pengcheng & family',
 'Wen Yibo & family',
 'Anne Werninghaus',
 'Dan Wilks',
 'Wong Hei & family',
 'Wong Hong King',
 'Wu Chung-yi',
 'Wu Eddie Yongming',
 'Eugene Wu',
 'Wu Wei',
 'Xiao Guoqing',
 'George Yancopoulos',
 'Yao Lisheng',
 'Yu Faxiang',
 'Yuan Jinhua',
 'Igor Yusufov',
 'Zan Shengda',
 'Zeng Huansha',
 'Zhang Xuewu',
 'Zhang Yuxiang & family',
 'Zhao Tongtong',
 'Tony Zhao',
 'Zhong Peifeng',
 'Zhou Ping & family',
 'Zhou Yahui',
 'Boris Zingarevich',
 'Ahmet Nazif Zorlu',
 'A. Jayson Adair',
 'Albert Avdolyan',
 'Baiju Bhatt',
 "Wilbur 'Ed' Bosarge, Jr.",
 'Ina Chan',
 'Chang Byung-gyu',
 'Chung Mong-joon',
 'Carmen Daurella Aguilera',
 'GT Dave',
 'Mukand Lal Dua',
 'Ramesh Kumar Dua',
 'Jose Elias',
 'Larry Fink',
 'Horst-Otto Gerberding',
 'Gim Seong-gon',
 'Gou Yiqun',
 'Clelia Haji-Ioannou',
 'Hang Hong',
 'Ronnen Harary',
 'David Harding',
 'David Helgason',
 'Hou Jianbin',
 'Hur Young-in',
 'Jiang Long',
 'Morris Kahn',
 'Ashok Kajaria',
 'T.S. Kalyanaraman',
 'Kim Kardashian West',
 'David Katzman',
 'Bom Kim',
 'Masatoshi Kumagai',
 'Lev Kvetnoi',
 'Vladimir Leschikov',
 'Li Yinan',
 'Liu Qingfeng',
 'Jose Llado Fernandez-Urrutia',
 'Kenneth Lo',
 'Ma Hong',
 'Sergei Makhlai',
 'Rafique Malik',
 'Mao Huihua',
 'Michael McCain',
 'Mofatraj Munot',
 'Vitaly Orlov',
 'George Pedersen',
 'David Penaloza Alanis',
 'Tyler Perry',
 'Maria Pinheiro',
 'Anton Rabie',
 'Jorge Rodriguez Rodriguez',
 'Hartley Rogers',
 'Alan Rydge',
 'Shin Dong-joo',
 'Scott Smith',
 'Zakhar Smushkin',
 'Marco Squinzi',
 'Veronica Squinzi',
 'Axel Stawski',
 'Manny Stul',
 'Vlad Tenev',
 'Rit Thirakomen',
 'Tong Judy Wenhong',
 'Tsai Chi-jui',
 'Surin Upatkoon',
 'Ruben Vardanyan',
 'Murat Vargi',
 'Vlad Vendrow & family',
 'Wang Qiangxiang',
 'Wang Wenjian',
 'J. Wayne Weaver',
 'Sandy Weill',
 'Xia Zhisheng & family',
 'Xu Jin',
 'Vadim Yakunin',
 'Mark Haoyong Yang',
 'Yao Hsiao Tung',
 'Yu De-Chao',
 'Daniel Yong Zhang',
 'Zhang Yuqiang',
 'Zhao Meiguang',
 'Zhong Naixiong',
 'Zhou Wei family',
 'Martha MacMillan',
 'William MacMillan',
 'Yasseen Mansour',
 'John Martin',
 'Carsten Maschmeyer',
 'Bruce Mathieson',
 'John McConnell & family',
 'Takanori Nakamura',
 'Bruce Nordstrom',
 'Madeleine Olsson Ericksson',
 'Ou Xueming',
 'Mats Paulsson & family',
 'Peng Hao',
 'Ricardo Po Sr. & family',
 'Forrest Preston',
 'Enrico Preziosi',
 'Pu Shulin',
 'Qiu Lingyun',
 'Vera Rechulski Santo Domingo',
 'M.Satyanarayana Reddy',
 'Ruan Hongxian & family',
 'Chanchai Ruayrungruang',
 'Daisuke Sasaki',
 'Jack Schuler',
 'Neerja Sethi',
 'Shin Dong-guk',
 'Edgar Sia II',
 'Michael S. Smith',
 'Su Rubo',
 'Sun Xishuang',
 'Sehat Sutardja',
 'Susanto Suwarto',
 'Tan Eng Kee',
 'Tan Yu Wei',
 'Yoshikazu Tanaka',
 'Hary Tanoesoedibjo',
 'Mehmet Sinan Tara',
 'Shirou Terashita',
 'Carl Thoma',
 'Tseng Sing-ai',
 'Sunil Vachani',
 'Jan Van Geet',
 'Sekar Vembu',
 'Wang Han',
 'Wang Jianliang',
 'Wang Kunxiao',
 'Wen Pengcheng & family',
 'Wen Yibo & family',
 'Anne Werninghaus',
 'Dan Wilks',
 'Wong Hei & family',
 'Wong Hong King',
 'Wu Chung-yi',
 'Wu Eddie Yongming',
 'Eugene Wu',
 'Wu Wei',
 'Xiao Guoqing',
 'George Yancopoulos',
 'Yao Lisheng',
 'Yu Faxiang',
 'Yuan Jinhua',
 'Igor Yusufov',
 'Zan Shengda',
 'Zeng Huansha',
 'Zhang Xuewu',
 'Zhang Yuxiang & family',
 'Zhao Tongtong',
 'Tony Zhao',
 'Zhong Peifeng',
 'Zhou Ping & family',
 'Zhou Yahui',
 'Boris Zingarevich',
 'Ahmet Nazif Zorlu',
 'A. Jayson Adair',
 'Albert Avdolyan',
 'Baiju Bhatt',
 "Wilbur 'Ed' Bosarge, Jr.",
 'Ina Chan',
 'Chang Byung-gyu',
 'Chung Mong-joon',
 'Carmen Daurella Aguilera',
 'GT Dave',
 'Mukand Lal Dua',
 'Ramesh Kumar Dua',
 'Jose Elias',
 'Larry Fink',
 'Horst-Otto Gerberding',
 'Gim Seong-gon',
 'Gou Yiqun',
 'Clelia Haji-Ioannou',
 'Hang Hong',
 'Ronnen Harary',
 'David Harding',
 'David Helgason',
 'Hou Jianbin',
 'Hur Young-in',
 'Jiang Long',
 'Morris Kahn',
 'Ashok Kajaria',
 'T.S. Kalyanaraman',
 'Kim Kardashian West',
 'David Katzman',
 'Bom Kim',
 'Masatoshi Kumagai',
 'Lev Kvetnoi',
 'Vladimir Leschikov',
 'Li Yinan',
 'Liu Qingfeng',
 'Jose Llado Fernandez-Urrutia',
 'Kenneth Lo',
 'Ma Hong',
 'Sergei Makhlai',
 'Rafique Malik',
 'Mao Huihua',
 'Michael McCain',
 'Mofatraj Munot',
 'Vitaly Orlov',
 'George Pedersen',
 'David Penaloza Alanis',
 'Tyler Perry',
 'Maria Pinheiro',
 'Anton Rabie',
 'Jorge Rodriguez Rodriguez',
 'Hartley Rogers',
 'Alan Rydge',
 'Shin Dong-joo',
 'Scott Smith',
 'Zakhar Smushkin',
 'Marco Squinzi',
 'Veronica Squinzi',
 'Axel Stawski',
 'Manny Stul',
 'Vlad Tenev',
 'Rit Thirakomen',
 'Tong Judy Wenhong',
 'Tsai Chi-jui',
 'Surin Upatkoon',
 'Ruben Vardanyan',
 'Murat Vargi',
 'Vlad Vendrow & family',
 'Wang Qiangxiang',
 'Wang Wenjian',
 'J. Wayne Weaver',
 'Sandy Weill',
 'Xia Zhisheng & family',
 'Xu Jin',
 'Vadim Yakunin',
 'Mark Haoyong Yang',
 'Yao Hsiao Tung',
 'Yu De-Chao',
 'Daniel Yong Zhang',
 'Zhang Yuqiang',
 'Zhao Meiguang',
 'Zhong Naixiong',
 'Zhou Wei family',
 'Martha MacMillan',
 'William MacMillan',
 'Yasseen Mansour',
 'John Martin',
 'Carsten Maschmeyer',
 'Bruce Mathieson',
 'John McConnell & family',
 'Takanori Nakamura',
 'Bruce Nordstrom',
 'Madeleine Olsson Ericksson',
 'Ou Xueming',
 'Mats Paulsson & family',
 'Peng Hao',
 'Ricardo Po Sr. & family',
 'Forrest Preston',
 'Enrico Preziosi',
 'Pu Shulin',
 'Qiu Lingyun',
 'Vera Rechulski Santo Domingo',
 'M.Satyanarayana Reddy',
 'Ruan Hongxian & family',
 'Chanchai Ruayrungruang',
 'Daisuke Sasaki',
 'Jack Schuler',
 'Neerja Sethi',
 'Shin Dong-guk',
 'Edgar Sia II',
 'Michael S. Smith',
 'Su Rubo',
 'Sun Xishuang',
 'Sehat Sutardja',
 'Susanto Suwarto',
 'Tan Eng Kee',
 'Tan Yu Wei',
 'Yoshikazu Tanaka',
 'Hary Tanoesoedibjo',
 'Mehmet Sinan Tara',
 'Shirou Terashita',
 'Carl Thoma',
 'Tseng Sing-ai',
 'Sunil Vachani',
 'Jan Van Geet',
 'Sekar Vembu',
 'Wang Han',
 'Wang Jianliang',
 'Wang Kunxiao',
 'Wen Pengcheng & family',
 'Wen Yibo & family',
 'Anne Werninghaus',
 'Dan Wilks',
 'Wong Hei & family',
 'Wong Hong King',
 'Wu Chung-yi',
 'Wu Eddie Yongming',
 'Eugene Wu',
 'Wu Wei',
 'Xiao Guoqing',
 'George Yancopoulos',
 'Yao Lisheng',
 'Yu Faxiang',
 'Yuan Jinhua',
 'Igor Yusufov',
 'Zan Shengda',
 'Zeng Huansha',
 'Zhang Xuewu',
 'Zhang Yuxiang & family',
 'Zhao Tongtong',
 'Tony Zhao',
 'Zhong Peifeng',
 'Zhou Ping & family',
 ...]

In [37]:
len(names)

2015

In [17]:
for i in range(0,13):
    prev_button=driver.find_element_by_xpath("//div[@class='pagination']//button[1]//div//i")
    try:
        prev_button.click()  
    except:
        time.sleep(1)

In [18]:
net_worths=[]
for page in range(0,13):
    net_worth=driver.find_elements_by_xpath("//div[@class='netWorth']")
    for i in net_worth:
        net_worths.append(i.text)
    nxt_button=driver.find_element_by_xpath("//div[@class='pagination']//button[2]//div//i")
    try:
        nxt_button.click()  
    except:
        time.sleep(1)

In [19]:
net_worths

['$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 '$1.1 B',
 ...]

In [38]:
len(net_worths)

2015

In [20]:
for i in range(0,13):
    prev_button=driver.find_element_by_xpath("//div[@class='pagination']//button[1]//div//i")
    try:
        prev_button.click()  
    except:
        time.sleep(1)

In [21]:
Ages=[]
for page in range(0,13):
    Age=driver.find_elements_by_xpath("//div[@class='age']")
    for i in Age:
        Ages.append(i.text)
    nxt_button=driver.find_element_by_xpath("//div[@class='pagination']//button[2]//div//i")
    try:
        nxt_button.click()  
    except:
        time.sleep(1)

In [22]:
Ages

['69',
 '66',
 '59',
 '69',
 '61',
 '77',
 '67',
 '48',
 '87',
 '76',
 '72',
 '76',
 '53',
 '90',
 '88',
 '73',
 '65',
 '45',
 '72',
 '63',
 '54',
 '67',
 '40',
 '80',
 '66',
 '71',
 '44',
 '65',
 '66',
 '67',
 '59',
 '65',
 '51',
 '48',
 '44',
 '55',
 '62',
 '62',
 '72',
 'N/A',
 '52',
 '49',
 '49',
 '33',
 '45',
 '51',
 '58',
 '55',
 '35',
 '64',
 '59',
 '59',
 '65',
 '46',
 '75',
 '53',
 '52',
 '61',
 '51',
 '49',
 '61',
 '64',
 '58',
 '53',
 '46',
 '56',
 '54',
 '49',
 '58',
 '58',
 '44',
 '61',
 '76',
 '51',
 '50',
 '36',
 '81',
 '67',
 '47',
 '69',
 'N/A',
 '44',
 '72',
 '67',
 '44',
 '68',
 '68',
 '67',
 '48',
 '50',
 '53',
 '49',
 '59',
 '43',
 '39',
 '71',
 '47',
 '91',
 '73',
 '73',
 '40',
 '61',
 '42',
 '57',
 '55',
 '64',
 '51',
 '48',
 '87',
 '82',
 '50',
 '52',
 '70',
 '59',
 'N/A',
 '76',
 '56',
 '85',
 '47',
 '51',
 'N/A',
 '49',
 '75',
 '61',
 '68',
 '67',
 '71',
 '59',
 '49',
 '49',
 '70',
 '71',
 '34',
 '69',
 '51',
 '81',
 '71',
 '52',
 '73',
 '53',
 '49',
 '74',
 '85',
 '88',
 '79',
 '56',
 '58',
 '46',
 '81',
 '57',
 '49',
 '65',
 '58',
 '58',
 '54',
 '69',
 '66',
 '59',
 '69',
 '61',
 '77',
 '67',
 '48',
 '87',
 '76',
 '72',
 '76',
 '53',
 '90',
 '88',
 '73',
 '65',
 '45',
 '72',
 '63',
 '54',
 '67',
 '40',
 '80',
 '66',
 '71',
 '44',
 '65',
 '66',
 '67',
 '59',
 '65',
 '51',
 '48',
 '44',
 '55',
 '62',
 '62',
 '72',
 'N/A',
 '52',
 '49',
 '49',
 '33',
 '45',
 '51',
 '58',
 '55',
 '35',
 '64',
 '59',
 '59',
 '65',
 '46',
 '75',
 '53',
 '52',
 '61',
 '51',
 '49',
 '61',
 '64',
 '58',
 '53',
 '46',
 '56',
 '54',
 '49',
 '58',
 '58',
 '44',
 '61',
 '76',
 '51',
 '50',
 '36',
 '81',
 '67',
 '47',
 '69',
 'N/A',
 '44',
 '72',
 '67',
 '44',
 '68',
 '68',
 '67',
 '48',
 '50',
 '53',
 '49',
 '59',
 '43',
 '39',
 '71',
 '47',
 '91',
 '73',
 '73',
 '40',
 '61',
 '42',
 '57',
 '55',
 '64',
 '51',
 '48',
 '87',
 '82',
 '50',
 '52',
 '70',
 '59',
 'N/A',
 '76',
 '56',
 '85',
 '47',
 '51',
 'N/A',
 '49',
 '75',
 '61',
 '68',
 '67',
 '71',
 '59',
 '49',
 '49',
 '70',
 '71',
 '34',
 '69',
 '51',
 '81',
 '71',
 '52',
 '73',
 '53',
 '49',
 '74',
 '85',
 '88',
 '79',
 '56',
 '58',
 '46',
 '81',
 '57',
 '49',
 '65',
 '58',
 '58',
 '54',
 '69',
 '66',
 '59',
 '69',
 '61',
 '77',
 '67',
 '48',
 '87',
 '76',
 '72',
 '76',
 '53',
 '90',
 '88',
 '73',
 '65',
 '45',
 '72',
 '63',
 '54',
 '67',
 '40',
 '80',
 '66',
 '71',
 '44',
 '65',
 '66',
 '67',
 '59',
 '65',
 '51',
 '48',
 '44',
 '55',
 '62',
 '62',
 '72',
 'N/A',
 '52',
 '49',
 '49',
 '33',
 '45',
 '51',
 '58',
 '55',
 '35',
 '64',
 '59',
 '59',
 '65',
 '46',
 '75',
 '53',
 '52',
 '61',
 '51',
 '49',
 '61',
 '64',
 '58',
 '53',
 '46',
 '56',
 '54',
 '49',
 '58',
 '58',
 '44',
 '61',
 '76',
 '51',
 '50',
 '36',
 '81',
 '67',
 '47',
 '69',
 'N/A',
 '44',
 '72',
 '67',
 '44',
 '68',
 '68',
 '67',
 '48',
 '50',
 '53',
 '49',
 '59',
 '43',
 '39',
 '71',
 '47',
 '91',
 '73',
 '73',
 '40',
 '61',
 '42',
 '57',
 '55',
 '64',
 '51',
 '48',
 '87',
 '82',
 '50',
 '52',
 '70',
 '59',
 'N/A',
 '76',
 '56',
 '85',
 '47',
 '51',
 'N/A',
 '49',
 '75',
 '61',
 '68',
 '67',
 '71',
 '59',
 '49',
 '49',
 '70',
 '71',
 '34',
 '69',
 '51',
 '81',
 '71',
 '52',
 '73',
 '53',
 '49',
 '74',
 '85',
 '88',
 '79',
 '56',
 '58',
 '46',
 '81',
 '57',
 '49',
 '65',
 '58',
 '58',
 '54',
 '69',
 '66',
 '59',
 '69',
 '61',
 '77',
 '67',
 '48',
 '87',
 '76',
 '72',
 '76',
 '53',
 '90',
 '88',
 '73',
 '65',
 '45',
 '72',
 '63',
 '54',
 '67',
 '40',
 '80',
 '66',
 '71',
 '44',
 '65',
 '66',
 '67',
 '59',
 '65',
 '51',
 '48',
 '44',
 '55',
 '62',
 '62',
 '72',
 'N/A',
 '52',
 '49',
 '49',
 '33',
 '45',
 '51',
 '58',
 '55',
 '35',
 '64',
 '59',
 '59',
 '65',
 '46',
 '75',
 '53',
 '52',
 '61',
 '51',
 '49',
 '61',
 '64',
 '58',
 '53',
 '46',
 '56',
 '54',
 '49',
 '58',
 '58',
 '44',
 '61',
 '76',
 '51',
 '50',
 '36',
 '81',
 '67',
 '47',
 '69',
 'N/A',
 '44',
 '72',
 '67',
 '44',
 '68',
 '68',
 '67',
 '48',
 '50',
 '53',
 '49',
 '59',
 '43',
 '39',
 '71',
 '47',
 '91',
 '73',
 '73',
 '40',
 '61',
 '42',
 '57',
 '55',
 '64',
 '51',
 '48',
 '87',
 '82',
 '50',
 '52',
 '70',
 '59',
 'N/A',
 '76',
 '56',
 '85',
 '47',
 '51',
 'N/A',
 '49',
 '75',
 '61',
 '68',
 '67',
 '71',
 '59',
 '49',
 '49',
 '70',
 '71',
 '34',
 '69',
 '51',
 '81',
 '71',
 '52',
 '73',
 '53',
 '49',
 '74',
 '85',
 '88',
 '79',
 '56',
 '58',
 '46',
 '81',
 '57',
 '49',
 '65',
 '58',
 '58',
 '54',
 '69',
 '66',
 '59',
 '69',
 '61',
 '77',
 '67',
 '48',
 '87',
 '76',
 '72',
 '76',
 '53',
 '90',
 '88',
 '73',
 '65',
 '45',
 '72',
 '63',
 '54',
 '67',
 '40',
 '80',
 '66',
 '71',
 '44',
 '65',
 '66',
 '67',
 '59',
 '65',
 '51',
 '48',
 '44',
 '55',
 '62',
 '62',
 '72',
 'N/A',
 '52',
 '49',
 '49',
 '33',
 '45',
 '51',
 '58',
 '55',
 '35',
 '64',
 '59',
 '59',
 '65',
 '46',
 '75',
 '53',
 '52',
 '61',
 '51',
 '49',
 '61',
 '64',
 '58',
 '53',
 '46',
 '56',
 '54',
 '49',
 '58',
 '58',
 '44',
 '61',
 '76',
 '51',
 '50',
 '36',
 '81',
 '67',
 '47',
 '69',
 'N/A',
 '44',
 '72',
 '67',
 '44',
 '68',
 '68',
 '67',
 '48',
 '50',
 '53',
 '49',
 '59',
 '43',
 '39',
 '71',
 '47',
 '91',
 '73',
 '73',
 '40',
 '61',
 '42',
 '57',
 '55',
 '64',
 '51',
 '48',
 '87',
 '82',
 '50',
 '52',
 '70',
 '59',
 'N/A',
 '76',
 '56',
 '85',
 '47',
 '51',
 'N/A',
 '49',
 '75',
 '61',
 '68',
 '67',
 '71',
 '59',
 '49',
 '49',
 '70',
 '71',
 '34',
 '69',
 '51',
 '81',
 '71',
 '52',
 '73',
 '53',
 '49',
 '74',
 '85',
 '88',
 '79',
 '56',
 '58',
 '46',
 '81',
 '57',
 '49',
 '65',
 '58',
 '58',
 '54',
 '69',
 '66',
 '59',
 '69',
 '61',
 '77',
 '67',
 '48',
 '87',
 '76',
 '72',
 '76',
 '53',
 '90',
 '88',
 '73',
 '65',
 '45',
 '72',
 '63',
 '54',
 '67',
 '40',
 '80',
 '66',
 '71',
 '44',
 '65',
 '66',
 '67',
 '59',
 '65',
 '51',
 '48',
 '44',
 '55',
 '62',
 '62',
 '72',
 'N/A',
 '52',
 '49',
 '49',
 '33',
 '45',
 '51',
 '58',
 '55',
 '35',
 '64',
 '59',
 '59',
 '65',
 '46',
 '75',
 '53',
 '52',
 '61',
 '51',
 '49',
 '61',
 '64',
 '58',
 '53',
 '46',
 '56',
 '54',
 '49',
 '58',
 '58',
 '44',
 '61',
 '76',
 '51',
 '50',
 '36',
 '81',
 '67',
 '47',
 '69',
 'N/A',
 '44',
 '72',
 '67',
 '44',
 '68',
 '68',
 '67',
 '48',
 '50',
 '53',
 '49',
 '59',
 '43',
 '39',
 '71',
 '47',
 '91',
 '73',
 '73',
 '40',
 '61',
 '42',
 '57',
 '55',
 '64',
 '51',
 '48',
 '87',
 '82',
 '50',
 '52',
 '70',
 '59',
 'N/A',
 '76',
 '56',
 '85',
 '47',
 '51',
 'N/A',
 '49',
 '75',
 '61',
 '68',
 '67',
 '71',
 '59',
 '49',
 '49',
 '70',
 '71',
 '34',
 '69',
 '51',
 '81',
 '71',
 '52',
 '73',
 '53',
 '49',
 '74',
 '85',
 '88',
 '79',
 '56',
 '58',
 '46',
 '81',
 '57',
 '49',
 '65',
 '58',
 '58',
 '54',
 '69',
 '66',
 '59',
 '69',
 '61',
 '77',
 '67',
 '48',
 '87',
 '76',
 '72',
 '76',
 '53',
 '90',
 '88',
 '73',
 '65',
 '45',
 '72',
 '63',
 '54',
 '67',
 '40',
 '80',
 '66',
 '71',
 '44',
 '65',
 '66',
 '67',
 '59',
 '65',
 '51',
 '48',
 '44',
 '55',
 '62',
 '62',
 '72',
 'N/A',
 '52',
 '49',
 '49',
 '33',
 '45',
 '51',
 '58',
 '55',
 '35',
 '64',
 '59',
 '59',
 '65',
 '46',
 '75',
 '53',
 '52',
 '61',
 '51',
 '49',
 '61',
 '64',
 '58',
 '53',
 '46',
 '56',
 '54',
 '49',
 '58',
 '58',
 ...]

In [23]:
for i in range(0,13):
    prev_button=driver.find_element_by_xpath("//div[@class='pagination']//button[1]//div//i")
    try:
        prev_button.click()  
    except:
        time.sleep(1)

In [24]:
citizens=[]
for page in range(0,13):
    citizen=driver.find_elements_by_xpath("//div[@class='countryOfCitizenship']")
    for i in citizen:
        citizens.append(i.text)
    nxt_button=driver.find_element_by_xpath("//div[@class='pagination']//button[2]//div//i")
    try:
        nxt_button.click()  
    except:
        time.sleep(1)

In [25]:
citizens

['United States',
 'United States',
 'Egypt',
 'United States',
 'Germany',
 'Australia',
 'United States',
 'Japan',
 'United States',
 'Sweden',
 'China',
 'Sweden',
 'China',
 'Philippines',
 'United States',
 'Italy',
 'China',
 'China',
 'Brazil',
 'India',
 'China',
 'China',
 'Japan',
 'United States',
 'United States',
 'South Korea',
 'Philippines',
 'United States',
 'China',
 'China',
 'United States',
 'Indonesia',
 'Malaysia',
 'Malaysia',
 'Japan',
 'Indonesia',
 'Turkey',
 'Japan',
 'United States',
 'Taiwan',
 'India',
 'Belgium',
 'India',
 'China',
 'China',
 'China',
 'China',
 'China',
 'Brazil',
 'United States',
 'China',
 'China',
 'Taiwan',
 'China',
 'Taiwan',
 'China',
 'China',
 'United States',
 'China',
 'China',
 'China',
 'Russia',
 'China',
 'China',
 'China',
 'China',
 'Canada',
 'China',
 'United States',
 'China',
 'China',
 'Russia',
 'Turkey',
 'United States',
 'Russia',
 'United States',
 'United States',
 'Hong Kong',
 'South Korea',
 'South Korea',
 'Spain',
 'United States',
 'India',
 'India',
 'Spain',
 'United States',
 'Germany',
 'South Korea',
 'China',
 'Cyprus',
 'China',
 'Canada',
 'United Kingdom',
 'Iceland',
 'China',
 'South Korea',
 'China',
 'Israel',
 'India',
 'India',
 'United States',
 'United States',
 'United States',
 'Japan',
 'Russia',
 'Russia',
 'China',
 'China',
 'Spain',
 'United Kingdom',
 'China',
 'Russia',
 'India',
 'Canada',
 'Canada',
 'India',
 'Russia',
 'United States',
 'Mexico',
 'United States',
 'Brazil',
 'Canada',
 'Peru',
 'United States',
 'Australia',
 'South Korea',
 'United States',
 'Russia',
 'Italy',
 'Italy',
 'United States',
 'Australia',
 'United States',
 'Thailand',
 'China',
 'Taiwan',
 'Thailand',
 'Russia',
 'Turkey',
 'United States',
 'China',
 'China',
 'United States',
 'United States',
 'China',
 'China',
 'Russia',
 'China',
 'Singapore',
 'United States',
 'China',
 'China',
 'China',
 'China',
 'China',
 'United States',
 'United States',
 'Egypt',
 'United States',
 'Germany',
 'Australia',
 'United States',
 'Japan',
 'United States',
 'Sweden',
 'China',
 'Sweden',
 'China',
 'Philippines',
 'United States',
 'Italy',
 'China',
 'China',
 'Brazil',
 'India',
 'China',
 'China',
 'Japan',
 'United States',
 'United States',
 'South Korea',
 'Philippines',
 'United States',
 'China',
 'China',
 'United States',
 'Indonesia',
 'Malaysia',
 'Malaysia',
 'Japan',
 'Indonesia',
 'Turkey',
 'Japan',
 'United States',
 'Taiwan',
 'India',
 'Belgium',
 'India',
 'China',
 'China',
 'China',
 'China',
 'China',
 'Brazil',
 'United States',
 'China',
 'China',
 'Taiwan',
 'China',
 'Taiwan',
 'China',
 'China',
 'United States',
 'China',
 'China',
 'China',
 'Russia',
 'China',
 'China',
 'China',
 'China',
 'Canada',
 'China',
 'United States',
 'China',
 'China',
 'Russia',
 'Turkey',
 'United States',
 'Russia',
 'United States',
 'United States',
 'Hong Kong',
 'South Korea',
 'South Korea',
 'Spain',
 'United States',
 'India',
 'India',
 'Spain',
 'United States',
 'Germany',
 'South Korea',
 'China',
 'Cyprus',
 'China',
 'Canada',
 'United Kingdom',
 'Iceland',
 'China',
 'South Korea',
 'China',
 'Israel',
 'India',
 'India',
 'United States',
 'United States',
 'United States',
 'Japan',
 'Russia',
 'Russia',
 'China',
 'China',
 'Spain',
 'United Kingdom',
 'China',
 'Russia',
 'India',
 'Canada',
 'Canada',
 'India',
 'Russia',
 'United States',
 'Mexico',
 'United States',
 'Brazil',
 'Canada',
 'Peru',
 'United States',
 'Australia',
 'South Korea',
 'United States',
 'Russia',
 'Italy',
 'Italy',
 'United States',
 'Australia',
 'United States',
 'Thailand',
 'China',
 'Taiwan',
 'Thailand',
 'Russia',
 'Turkey',
 'United States',
 'China',
 'China',
 'United States',
 'United States',
 'China',
 'China',
 'Russia',
 'China',
 'Singapore',
 'United States',
 'China',
 'China',
 'China',
 'China',
 'China',
 'United States',
 'United States',
 'Egypt',
 'United States',
 'Germany',
 'Australia',
 'United States',
 'Japan',
 'United States',
 'Sweden',
 'China',
 'Sweden',
 'China',
 'Philippines',
 'United States',
 'Italy',
 'China',
 'China',
 'Brazil',
 'India',
 'China',
 'China',
 'Japan',
 'United States',
 'United States',
 'South Korea',
 'Philippines',
 'United States',
 'China',
 'China',
 'United States',
 'Indonesia',
 'Malaysia',
 'Malaysia',
 'Japan',
 'Indonesia',
 'Turkey',
 'Japan',
 'United States',
 'Taiwan',
 'India',
 'Belgium',
 'India',
 'China',
 'China',
 'China',
 'China',
 'China',
 'Brazil',
 'United States',
 'China',
 'China',
 'Taiwan',
 'China',
 'Taiwan',
 'China',
 'China',
 'United States',
 'China',
 'China',
 'China',
 'Russia',
 'China',
 'China',
 'China',
 'China',
 'Canada',
 'China',
 'United States',
 'China',
 'China',
 'Russia',
 'Turkey',
 'United States',
 'Russia',
 'United States',
 'United States',
 'Hong Kong',
 'South Korea',
 'South Korea',
 'Spain',
 'United States',
 'India',
 'India',
 'Spain',
 'United States',
 'Germany',
 'South Korea',
 'China',
 'Cyprus',
 'China',
 'Canada',
 'United Kingdom',
 'Iceland',
 'China',
 'South Korea',
 'China',
 'Israel',
 'India',
 'India',
 'United States',
 'United States',
 'United States',
 'Japan',
 'Russia',
 'Russia',
 'China',
 'China',
 'Spain',
 'United Kingdom',
 'China',
 'Russia',
 'India',
 'Canada',
 'Canada',
 'India',
 'Russia',
 'United States',
 'Mexico',
 'United States',
 'Brazil',
 'Canada',
 'Peru',
 'United States',
 'Australia',
 'South Korea',
 'United States',
 'Russia',
 'Italy',
 'Italy',
 'United States',
 'Australia',
 'United States',
 'Thailand',
 'China',
 'Taiwan',
 'Thailand',
 'Russia',
 'Turkey',
 'United States',
 'China',
 'China',
 'United States',
 'United States',
 'China',
 'China',
 'Russia',
 'China',
 'Singapore',
 'United States',
 'China',
 'China',
 'China',
 'China',
 'China',
 'United States',
 'United States',
 'Egypt',
 'United States',
 'Germany',
 'Australia',
 'United States',
 'Japan',
 'United States',
 'Sweden',
 'China',
 'Sweden',
 'China',
 'Philippines',
 'United States',
 'Italy',
 'China',
 'China',
 'Brazil',
 'India',
 'China',
 'China',
 'Japan',
 'United States',
 'United States',
 'South Korea',
 'Philippines',
 'United States',
 'China',
 'China',
 'United States',
 'Indonesia',
 'Malaysia',
 'Malaysia',
 'Japan',
 'Indonesia',
 'Turkey',
 'Japan',
 'United States',
 'Taiwan',
 'India',
 'Belgium',
 'India',
 'China',
 'China',
 'China',
 'China',
 'China',
 'Brazil',
 'United States',
 'China',
 'China',
 'Taiwan',
 'China',
 'Taiwan',
 'China',
 'China',
 'United States',
 'China',
 'China',
 'China',
 'Russia',
 'China',
 'China',
 'China',
 'China',
 'Canada',
 'China',
 'United States',
 'China',
 'China',
 'Russia',
 'Turkey',
 'United States',
 'Russia',
 'United States',
 'United States',
 'Hong Kong',
 'South Korea',
 'South Korea',
 'Spain',
 'United States',
 'India',
 'India',
 'Spain',
 'United States',
 'Germany',
 'South Korea',
 'China',
 'Cyprus',
 'China',
 'Canada',
 'United Kingdom',
 'Iceland',
 'China',
 'South Korea',
 'China',
 'Israel',
 'India',
 'India',
 'United States',
 'United States',
 'United States',
 'Japan',
 'Russia',
 'Russia',
 'China',
 'China',
 'Spain',
 'United Kingdom',
 'China',
 'Russia',
 'India',
 'Canada',
 'Canada',
 'India',
 'Russia',
 'United States',
 'Mexico',
 'United States',
 'Brazil',
 'Canada',
 'Peru',
 'United States',
 'Australia',
 'South Korea',
 'United States',
 'Russia',
 'Italy',
 'Italy',
 'United States',
 'Australia',
 'United States',
 'Thailand',
 'China',
 'Taiwan',
 'Thailand',
 'Russia',
 'Turkey',
 'United States',
 'China',
 'China',
 'United States',
 'United States',
 'China',
 'China',
 'Russia',
 'China',
 'Singapore',
 'United States',
 'China',
 'China',
 'China',
 'China',
 'China',
 'United States',
 'United States',
 'Egypt',
 'United States',
 'Germany',
 'Australia',
 'United States',
 'Japan',
 'United States',
 'Sweden',
 'China',
 'Sweden',
 'China',
 'Philippines',
 'United States',
 'Italy',
 'China',
 'China',
 'Brazil',
 'India',
 'China',
 'China',
 'Japan',
 'United States',
 'United States',
 'South Korea',
 'Philippines',
 'United States',
 'China',
 'China',
 'United States',
 'Indonesia',
 'Malaysia',
 'Malaysia',
 'Japan',
 'Indonesia',
 'Turkey',
 'Japan',
 'United States',
 'Taiwan',
 'India',
 'Belgium',
 'India',
 'China',
 'China',
 'China',
 'China',
 'China',
 'Brazil',
 'United States',
 'China',
 'China',
 'Taiwan',
 'China',
 'Taiwan',
 'China',
 'China',
 'United States',
 'China',
 'China',
 'China',
 'Russia',
 'China',
 'China',
 'China',
 'China',
 'Canada',
 'China',
 'United States',
 'China',
 'China',
 'Russia',
 'Turkey',
 'United States',
 'Russia',
 'United States',
 'United States',
 'Hong Kong',
 'South Korea',
 'South Korea',
 'Spain',
 'United States',
 'India',
 'India',
 'Spain',
 'United States',
 'Germany',
 'South Korea',
 'China',
 'Cyprus',
 'China',
 'Canada',
 'United Kingdom',
 'Iceland',
 'China',
 'South Korea',
 'China',
 'Israel',
 'India',
 'India',
 'United States',
 'United States',
 'United States',
 'Japan',
 'Russia',
 'Russia',
 'China',
 'China',
 'Spain',
 'United Kingdom',
 'China',
 'Russia',
 'India',
 'Canada',
 'Canada',
 'India',
 'Russia',
 'United States',
 'Mexico',
 'United States',
 'Brazil',
 'Canada',
 'Peru',
 'United States',
 'Australia',
 'South Korea',
 'United States',
 'Russia',
 'Italy',
 'Italy',
 'United States',
 'Australia',
 'United States',
 'Thailand',
 'China',
 'Taiwan',
 'Thailand',
 'Russia',
 'Turkey',
 'United States',
 'China',
 'China',
 'United States',
 'United States',
 'China',
 'China',
 'Russia',
 'China',
 'Singapore',
 'United States',
 'China',
 'China',
 'China',
 'China',
 'China',
 'United States',
 'United States',
 'Egypt',
 'United States',
 'Germany',
 'Australia',
 'United States',
 'Japan',
 'United States',
 'Sweden',
 'China',
 'Sweden',
 'China',
 'Philippines',
 'United States',
 'Italy',
 'China',
 'China',
 'Brazil',
 'India',
 'China',
 'China',
 'Japan',
 'United States',
 'United States',
 'South Korea',
 'Philippines',
 'United States',
 'China',
 'China',
 'United States',
 'Indonesia',
 'Malaysia',
 'Malaysia',
 'Japan',
 'Indonesia',
 'Turkey',
 'Japan',
 'United States',
 'Taiwan',
 'India',
 'Belgium',
 'India',
 'China',
 'China',
 'China',
 'China',
 'China',
 'Brazil',
 'United States',
 'China',
 'China',
 'Taiwan',
 'China',
 'Taiwan',
 'China',
 'China',
 'United States',
 'China',
 'China',
 'China',
 'Russia',
 'China',
 'China',
 'China',
 'China',
 'Canada',
 'China',
 'United States',
 'China',
 'China',
 'Russia',
 'Turkey',
 'United States',
 'Russia',
 'United States',
 'United States',
 'Hong Kong',
 'South Korea',
 'South Korea',
 'Spain',
 'United States',
 'India',
 'India',
 'Spain',
 'United States',
 'Germany',
 'South Korea',
 'China',
 'Cyprus',
 'China',
 'Canada',
 'United Kingdom',
 'Iceland',
 'China',
 'South Korea',
 'China',
 'Israel',
 'India',
 'India',
 'United States',
 'United States',
 'United States',
 'Japan',
 'Russia',
 'Russia',
 'China',
 'China',
 'Spain',
 'United Kingdom',
 'China',
 'Russia',
 'India',
 'Canada',
 'Canada',
 'India',
 'Russia',
 'United States',
 'Mexico',
 'United States',
 'Brazil',
 'Canada',
 'Peru',
 'United States',
 'Australia',
 'South Korea',
 'United States',
 'Russia',
 'Italy',
 'Italy',
 'United States',
 'Australia',
 'United States',
 'Thailand',
 'China',
 'Taiwan',
 'Thailand',
 'Russia',
 'Turkey',
 'United States',
 'China',
 'China',
 'United States',
 'United States',
 'China',
 'China',
 'Russia',
 'China',
 'Singapore',
 'United States',
 'China',
 'China',
 'China',
 'China',
 'China',
 'United States',
 'United States',
 'Egypt',
 'United States',
 'Germany',
 'Australia',
 'United States',
 'Japan',
 'United States',
 'Sweden',
 'China',
 'Sweden',
 'China',
 'Philippines',
 'United States',
 'Italy',
 'China',
 'China',
 'Brazil',
 'India',
 'China',
 'China',
 'Japan',
 'United States',
 'United States',
 'South Korea',
 'Philippines',
 'United States',
 'China',
 'China',
 'United States',
 'Indonesia',
 'Malaysia',
 'Malaysia',
 'Japan',
 'Indonesia',
 'Turkey',
 'Japan',
 'United States',
 'Taiwan',
 'India',
 'Belgium',
 'India',
 'China',
 'China',
 'China',
 'China',
 'China',
 'Brazil',
 'United States',
 'China',
 'China',
 'Taiwan',
 'China',
 'Taiwan',
 'China',
 'China',
 'United States',
 'China',
 'China',
 'China',
 'Russia',
 'China',
 'China',
 'China',
 'China',
 'Canada',
 'China',
 'United States',
 'China',
 ...]

In [26]:
for i in range(0,13):
    prev_button=driver.find_element_by_xpath("//div[@class='pagination']//button[1]//div//i")
    try:
        prev_button.click()  
    except:
        time.sleep(1)

In [27]:
sources=[]
for page in range(0,13):
    source=driver.find_elements_by_xpath("//div[@class='source-column']")
    for i in source:
        sources.append(i.text)
    nxt_button=driver.find_element_by_xpath("//div[@class='pagination']//button[2]//div//i")
    try:
        nxt_button.click()  
    except:
        time.sleep(1)

In [28]:
sources

['Cargill',
 'Cargill',
 'diversified',
 'pharmaceuticals',
 'finance and investments',
 'hotels',
 'steel',
 'cloud software',
 'Nordstrom department stores',
 'diversified',
 'real estate',
 'construction',
 'electronics',
 'canned food',
 'health care',
 'toys',
 'TV shows',
 'consumer technology',
 'beer',
 'pharmaceuticals',
 'pharmaceuticals',
 'real estate',
 'software',
 'pharmaceuticals',
 'IT consulting, outsourcing',
 'Pharmaceuticals',
 'fast food',
 'liquefied natural gas',
 'real estate',
 'real estate',
 'semiconductors',
 'media',
 'factory equipment',
 'retail',
 'social network',
 'media',
 'construction',
 'investor relations consulting',
 'investments',
 'petrochemicals',
 'electronics',
 'real estate developer',
 'business software',
 'airline',
 'consumer technology',
 'oilfield equipment',
 'agribusiness',
 'wastewater treatment',
 'industrial machinery',
 'natural gas',
 'conglomerate',
 'real estate',
 'manufacturing',
 'e-commerce',
 'finance',
 'education',
 'education',
 'pharmaceuticals',
 'electronics',
 'tourism, cultural industry',
 'Manufacturing',
 'oil & gas',
 'diversified',
 'real estate',
 'snacks',
 'apparel',
 'Hotels',
 'software',
 'semiconductor',
 'utilities',
 'online games',
 'pulp and paper, diversified',
 'diversified',
 'damaged cars',
 'oil, mining',
 'stock trading app',
 'high speed trading',
 'casinos',
 'Bluehole',
 'shipbuilding, industrial machines',
 'Coca-Cola bottler',
 'kombucha',
 'footwear',
 'footwear',
 'wind power',
 'money management',
 'flavors and fragrances',
 'renewable energy',
 'restaurant',
 'EasyJet',
 'machinery',
 'toys',
 'finance',
 'game software',
 'education',
 'bakeries, fast food',
 'Manufacturing',
 'software',
 'tiles',
 'jewelry',
 'cosmetics, reality TV',
 'teeth aligners',
 'online retailing',
 'internet services',
 'cement',
 'real estate',
 'Investments',
 'software',
 'construction',
 'textiles',
 'machinery',
 'fertilizers',
 'footwear',
 'pharmaceuticals',
 'packaged meats',
 'real estate',
 'fisheries',
 'defense contractor',
 'toll roads',
 'movies, television',
 'supermarkets',
 'toys',
 'processed milk',
 'asset management',
 'entertainment',
 'retail',
 'cloud computing',
 'pulp and paper, diversified',
 'chemical products',
 'chemical products',
 'real estate',
 'toys',
 'stock trading',
 'restaurants',
 'e-commerce',
 'shoes',
 'telecom, lotteries, insurance',
 'investment banking',
 'telecom',
 'software',
 'artificial turf',
 'optical devices',
 'Shoes',
 'Citigroup',
 'home appliances',
 'wine',
 'pharmacy',
 'e-commerce',
 'Manufacturing',
 'pharmaceuticals',
 'e-commerce',
 'Fiberglass',
 'gold mining',
 'conglomerate',
 'Software',
 'Cargill',
 'Cargill',
 'diversified',
 'pharmaceuticals',
 'finance and investments',
 'hotels',
 'steel',
 'cloud software',
 'Nordstrom department stores',
 'diversified',
 'real estate',
 'construction',
 'electronics',
 'canned food',
 'health care',
 'toys',
 'TV shows',
 'consumer technology',
 'beer',
 'pharmaceuticals',
 'pharmaceuticals',
 'real estate',
 'software',
 'pharmaceuticals',
 'IT consulting, outsourcing',
 'Pharmaceuticals',
 'fast food',
 'liquefied natural gas',
 'real estate',
 'real estate',
 'semiconductors',
 'media',
 'factory equipment',
 'retail',
 'social network',
 'media',
 'construction',
 'investor relations consulting',
 'investments',
 'petrochemicals',
 'electronics',
 'real estate developer',
 'business software',
 'airline',
 'consumer technology',
 'oilfield equipment',
 'agribusiness',
 'wastewater treatment',
 'industrial machinery',
 'natural gas',
 'conglomerate',
 'real estate',
 'manufacturing',
 'e-commerce',
 'finance',
 'education',
 'education',
 'pharmaceuticals',
 'electronics',
 'tourism, cultural industry',
 'Manufacturing',
 'oil & gas',
 'diversified',
 'real estate',
 'snacks',
 'apparel',
 'Hotels',
 'software',
 'semiconductor',
 'utilities',
 'online games',
 'pulp and paper, diversified',
 'diversified',
 'damaged cars',
 'oil, mining',
 'stock trading app',
 'high speed trading',
 'casinos',
 'Bluehole',
 'shipbuilding, industrial machines',
 'Coca-Cola bottler',
 'kombucha',
 'footwear',
 'footwear',
 'wind power',
 'money management',
 'flavors and fragrances',
 'renewable energy',
 'restaurant',
 'EasyJet',
 'machinery',
 'toys',
 'finance',
 'game software',
 'education',
 'bakeries, fast food',
 'Manufacturing',
 'software',
 'tiles',
 'jewelry',
 'cosmetics, reality TV',
 'teeth aligners',
 'online retailing',
 'internet services',
 'cement',
 'real estate',
 'Investments',
 'software',
 'construction',
 'textiles',
 'machinery',
 'fertilizers',
 'footwear',
 'pharmaceuticals',
 'packaged meats',
 'real estate',
 'fisheries',
 'defense contractor',
 'toll roads',
 'movies, television',
 'supermarkets',
 'toys',
 'processed milk',
 'asset management',
 'entertainment',
 'retail',
 'cloud computing',
 'pulp and paper, diversified',
 'chemical products',
 'chemical products',
 'real estate',
 'toys',
 'stock trading',
 'restaurants',
 'e-commerce',
 'shoes',
 'telecom, lotteries, insurance',
 'investment banking',
 'telecom',
 'software',
 'artificial turf',
 'optical devices',
 'Shoes',
 'Citigroup',
 'home appliances',
 'wine',
 'pharmacy',
 'e-commerce',
 'Manufacturing',
 'pharmaceuticals',
 'e-commerce',
 'Fiberglass',
 'gold mining',
 'conglomerate',
 'Software',
 'Cargill',
 'Cargill',
 'diversified',
 'pharmaceuticals',
 'finance and investments',
 'hotels',
 'steel',
 'cloud software',
 'Nordstrom department stores',
 'diversified',
 'real estate',
 'construction',
 'electronics',
 'canned food',
 'health care',
 'toys',
 'TV shows',
 'consumer technology',
 'beer',
 'pharmaceuticals',
 'pharmaceuticals',
 'real estate',
 'software',
 'pharmaceuticals',
 'IT consulting, outsourcing',
 'Pharmaceuticals',
 'fast food',
 'liquefied natural gas',
 'real estate',
 'real estate',
 'semiconductors',
 'media',
 'factory equipment',
 'retail',
 'social network',
 'media',
 'construction',
 'investor relations consulting',
 'investments',
 'petrochemicals',
 'electronics',
 'real estate developer',
 'business software',
 'airline',
 'consumer technology',
 'oilfield equipment',
 'agribusiness',
 'wastewater treatment',
 'industrial machinery',
 'natural gas',
 'conglomerate',
 'real estate',
 'manufacturing',
 'e-commerce',
 'finance',
 'education',
 'education',
 'pharmaceuticals',
 'electronics',
 'tourism, cultural industry',
 'Manufacturing',
 'oil & gas',
 'diversified',
 'real estate',
 'snacks',
 'apparel',
 'Hotels',
 'software',
 'semiconductor',
 'utilities',
 'online games',
 'pulp and paper, diversified',
 'diversified',
 'damaged cars',
 'oil, mining',
 'stock trading app',
 'high speed trading',
 'casinos',
 'Bluehole',
 'shipbuilding, industrial machines',
 'Coca-Cola bottler',
 'kombucha',
 'footwear',
 'footwear',
 'wind power',
 'money management',
 'flavors and fragrances',
 'renewable energy',
 'restaurant',
 'EasyJet',
 'machinery',
 'toys',
 'finance',
 'game software',
 'education',
 'bakeries, fast food',
 'Manufacturing',
 'software',
 'tiles',
 'jewelry',
 'cosmetics, reality TV',
 'teeth aligners',
 'online retailing',
 'internet services',
 'cement',
 'real estate',
 'Investments',
 'software',
 'construction',
 'textiles',
 'machinery',
 'fertilizers',
 'footwear',
 'pharmaceuticals',
 'packaged meats',
 'real estate',
 'fisheries',
 'defense contractor',
 'toll roads',
 'movies, television',
 'supermarkets',
 'toys',
 'processed milk',
 'asset management',
 'entertainment',
 'retail',
 'cloud computing',
 'pulp and paper, diversified',
 'chemical products',
 'chemical products',
 'real estate',
 'toys',
 'stock trading',
 'restaurants',
 'e-commerce',
 'shoes',
 'telecom, lotteries, insurance',
 'investment banking',
 'telecom',
 'software',
 'artificial turf',
 'optical devices',
 'Shoes',
 'Citigroup',
 'home appliances',
 'wine',
 'pharmacy',
 'e-commerce',
 'Manufacturing',
 'pharmaceuticals',
 'e-commerce',
 'Fiberglass',
 'gold mining',
 'conglomerate',
 'Software',
 'Cargill',
 'Cargill',
 'diversified',
 'pharmaceuticals',
 'finance and investments',
 'hotels',
 'steel',
 'cloud software',
 'Nordstrom department stores',
 'diversified',
 'real estate',
 'construction',
 'electronics',
 'canned food',
 'health care',
 'toys',
 'TV shows',
 'consumer technology',
 'beer',
 'pharmaceuticals',
 'pharmaceuticals',
 'real estate',
 'software',
 'pharmaceuticals',
 'IT consulting, outsourcing',
 'Pharmaceuticals',
 'fast food',
 'liquefied natural gas',
 'real estate',
 'real estate',
 'semiconductors',
 'media',
 'factory equipment',
 'retail',
 'social network',
 'media',
 'construction',
 'investor relations consulting',
 'investments',
 'petrochemicals',
 'electronics',
 'real estate developer',
 'business software',
 'airline',
 'consumer technology',
 'oilfield equipment',
 'agribusiness',
 'wastewater treatment',
 'industrial machinery',
 'natural gas',
 'conglomerate',
 'real estate',
 'manufacturing',
 'e-commerce',
 'finance',
 'education',
 'education',
 'pharmaceuticals',
 'electronics',
 'tourism, cultural industry',
 'Manufacturing',
 'oil & gas',
 'diversified',
 'real estate',
 'snacks',
 'apparel',
 'Hotels',
 'software',
 'semiconductor',
 'utilities',
 'online games',
 'pulp and paper, diversified',
 'diversified',
 'damaged cars',
 'oil, mining',
 'stock trading app',
 'high speed trading',
 'casinos',
 'Bluehole',
 'shipbuilding, industrial machines',
 'Coca-Cola bottler',
 'kombucha',
 'footwear',
 'footwear',
 'wind power',
 'money management',
 'flavors and fragrances',
 'renewable energy',
 'restaurant',
 'EasyJet',
 'machinery',
 'toys',
 'finance',
 'game software',
 'education',
 'bakeries, fast food',
 'Manufacturing',
 'software',
 'tiles',
 'jewelry',
 'cosmetics, reality TV',
 'teeth aligners',
 'online retailing',
 'internet services',
 'cement',
 'real estate',
 'Investments',
 'software',
 'construction',
 'textiles',
 'machinery',
 'fertilizers',
 'footwear',
 'pharmaceuticals',
 'packaged meats',
 'real estate',
 'fisheries',
 'defense contractor',
 'toll roads',
 'movies, television',
 'supermarkets',
 'toys',
 'processed milk',
 'asset management',
 'entertainment',
 'retail',
 'cloud computing',
 'pulp and paper, diversified',
 'chemical products',
 'chemical products',
 'real estate',
 'toys',
 'stock trading',
 'restaurants',
 'e-commerce',
 'shoes',
 'telecom, lotteries, insurance',
 'investment banking',
 'telecom',
 'software',
 'artificial turf',
 'optical devices',
 'Shoes',
 'Citigroup',
 'home appliances',
 'wine',
 'pharmacy',
 'e-commerce',
 'Manufacturing',
 'pharmaceuticals',
 'e-commerce',
 'Fiberglass',
 'gold mining',
 'conglomerate',
 'Software',
 'Cargill',
 'Cargill',
 'diversified',
 'pharmaceuticals',
 'finance and investments',
 'hotels',
 'steel',
 'cloud software',
 'Nordstrom department stores',
 'diversified',
 'real estate',
 'construction',
 'electronics',
 'canned food',
 'health care',
 'toys',
 'TV shows',
 'consumer technology',
 'beer',
 'pharmaceuticals',
 'pharmaceuticals',
 'real estate',
 'software',
 'pharmaceuticals',
 'IT consulting, outsourcing',
 'Pharmaceuticals',
 'fast food',
 'liquefied natural gas',
 'real estate',
 'real estate',
 'semiconductors',
 'media',
 'factory equipment',
 'retail',
 'social network',
 'media',
 'construction',
 'investor relations consulting',
 'investments',
 'petrochemicals',
 'electronics',
 'real estate developer',
 'business software',
 'airline',
 'consumer technology',
 'oilfield equipment',
 'agribusiness',
 'wastewater treatment',
 'industrial machinery',
 'natural gas',
 'conglomerate',
 'real estate',
 'manufacturing',
 'e-commerce',
 'finance',
 'education',
 'education',
 'pharmaceuticals',
 'electronics',
 'tourism, cultural industry',
 'Manufacturing',
 'oil & gas',
 'diversified',
 'real estate',
 'snacks',
 'apparel',
 'Hotels',
 'software',
 'semiconductor',
 'utilities',
 'online games',
 'pulp and paper, diversified',
 'diversified',
 'damaged cars',
 'oil, mining',
 'stock trading app',
 'high speed trading',
 'casinos',
 'Bluehole',
 'shipbuilding, industrial machines',
 'Coca-Cola bottler',
 'kombucha',
 'footwear',
 'footwear',
 'wind power',
 'money management',
 'flavors and fragrances',
 'renewable energy',
 'restaurant',
 'EasyJet',
 'machinery',
 'toys',
 'finance',
 'game software',
 'education',
 'bakeries, fast food',
 'Manufacturing',
 'software',
 'tiles',
 'jewelry',
 'cosmetics, reality TV',
 'teeth aligners',
 'online retailing',
 'internet services',
 'cement',
 'real estate',
 'Investments',
 'software',
 'construction',
 'textiles',
 'machinery',
 'fertilizers',
 'footwear',
 'pharmaceuticals',
 'packaged meats',
 'real estate',
 'fisheries',
 'defense contractor',
 'toll roads',
 'movies, television',
 'supermarkets',
 'toys',
 'processed milk',
 'asset management',
 'entertainment',
 'retail',
 'cloud computing',
 'pulp and paper, diversified',
 'chemical products',
 'chemical products',
 'real estate',
 'toys',
 'stock trading',
 'restaurants',
 'e-commerce',
 'shoes',
 'telecom, lotteries, insurance',
 'investment banking',
 'telecom',
 'software',
 'artificial turf',
 'optical devices',
 'Shoes',
 'Citigroup',
 'home appliances',
 'wine',
 'pharmacy',
 'e-commerce',
 'Manufacturing',
 'pharmaceuticals',
 'e-commerce',
 'Fiberglass',
 'gold mining',
 'conglomerate',
 'Software',
 'Cargill',
 'Cargill',
 'diversified',
 'pharmaceuticals',
 'finance and investments',
 'hotels',
 'steel',
 'cloud software',
 'Nordstrom department stores',
 'diversified',
 'real estate',
 'construction',
 'electronics',
 'canned food',
 'health care',
 'toys',
 'TV shows',
 'consumer technology',
 'beer',
 'pharmaceuticals',
 'pharmaceuticals',
 'real estate',
 'software',
 'pharmaceuticals',
 'IT consulting, outsourcing',
 'Pharmaceuticals',
 'fast food',
 'liquefied natural gas',
 'real estate',
 'real estate',
 'semiconductors',
 'media',
 'factory equipment',
 'retail',
 'social network',
 'media',
 'construction',
 'investor relations consulting',
 'investments',
 'petrochemicals',
 'electronics',
 'real estate developer',
 'business software',
 'airline',
 'consumer technology',
 'oilfield equipment',
 'agribusiness',
 'wastewater treatment',
 'industrial machinery',
 'natural gas',
 'conglomerate',
 'real estate',
 'manufacturing',
 'e-commerce',
 'finance',
 'education',
 'education',
 'pharmaceuticals',
 'electronics',
 'tourism, cultural industry',
 'Manufacturing',
 'oil & gas',
 'diversified',
 'real estate',
 'snacks',
 'apparel',
 'Hotels',
 'software',
 'semiconductor',
 'utilities',
 'online games',
 'pulp and paper, diversified',
 'diversified',
 'damaged cars',
 'oil, mining',
 'stock trading app',
 'high speed trading',
 'casinos',
 'Bluehole',
 'shipbuilding, industrial machines',
 'Coca-Cola bottler',
 'kombucha',
 'footwear',
 'footwear',
 'wind power',
 'money management',
 'flavors and fragrances',
 'renewable energy',
 'restaurant',
 'EasyJet',
 'machinery',
 'toys',
 'finance',
 'game software',
 'education',
 'bakeries, fast food',
 'Manufacturing',
 'software',
 'tiles',
 'jewelry',
 'cosmetics, reality TV',
 'teeth aligners',
 'online retailing',
 'internet services',
 'cement',
 'real estate',
 'Investments',
 'software',
 'construction',
 'textiles',
 'machinery',
 'fertilizers',
 'footwear',
 'pharmaceuticals',
 'packaged meats',
 'real estate',
 'fisheries',
 'defense contractor',
 'toll roads',
 'movies, television',
 'supermarkets',
 'toys',
 'processed milk',
 'asset management',
 'entertainment',
 'retail',
 'cloud computing',
 'pulp and paper, diversified',
 'chemical products',
 'chemical products',
 'real estate',
 'toys',
 'stock trading',
 'restaurants',
 'e-commerce',
 'shoes',
 'telecom, lotteries, insurance',
 'investment banking',
 'telecom',
 'software',
 'artificial turf',
 'optical devices',
 'Shoes',
 'Citigroup',
 'home appliances',
 'wine',
 'pharmacy',
 'e-commerce',
 'Manufacturing',
 'pharmaceuticals',
 'e-commerce',
 'Fiberglass',
 'gold mining',
 'conglomerate',
 'Software',
 'Cargill',
 'Cargill',
 'diversified',
 'pharmaceuticals',
 'finance and investments',
 'hotels',
 'steel',
 'cloud software',
 'Nordstrom department stores',
 'diversified',
 'real estate',
 'construction',
 'electronics',
 'canned food',
 'health care',
 'toys',
 'TV shows',
 'consumer technology',
 'beer',
 'pharmaceuticals',
 'pharmaceuticals',
 'real estate',
 'software',
 'pharmaceuticals',
 'IT consulting, outsourcing',
 'Pharmaceuticals',
 'fast food',
 'liquefied natural gas',
 'real estate',
 'real estate',
 'semiconductors',
 'media',
 'factory equipment',
 'retail',
 'social network',
 'media',
 'construction',
 'investor relations consulting',
 'investments',
 'petrochemicals',
 'electronics',
 'real estate developer',
 'business software',
 'airline',
 'consumer technology',
 'oilfield equipment',
 'agribusiness',
 'wastewater treatment',
 'industrial machinery',
 'natural gas',
 'conglomerate',
 'real estate',
 'manufacturing',
 'e-commerce',
 'finance',
 'education',
 'education',
 'pharmaceuticals',
 'electronics',
 'tourism, cultural industry',
 'Manufacturing',
 'oil & gas',
 'diversified',
 'real estate',
 'snacks',
 'apparel',
 'Hotels',
 'software',
 'semiconductor',
 'utilities',
 ...]

In [29]:
for i in range(0,13):
    prev_button=driver.find_element_by_xpath("//div[@class='pagination']//button[1]//div//i")
    try:
        prev_button.click()  
    except:
        time.sleep(1)

In [32]:
Industrys=[]
for page in range(0,13):
    Industry=driver.find_elements_by_xpath("//div[@class='category']")
    for i in Industry:
        Industrys.append(i.text)
    nxt_button=driver.find_element_by_xpath("//div[@class='pagination']//button[2]//div//i")
    try:
        nxt_button.click()  
    except:
        time.sleep(1)

In [33]:
Industrys

['Food & Beverage',
 'Food & Beverage',
 'Diversified',
 'Healthcare',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Real Estate',
 'Construction & Engineering',
 'Manufacturing',
 'Food & Beverage',
 'Healthcare',
 'Fashion & Retail',
 'Media & Entertainment',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Healthcare',
 'Real Estate',
 'Technology',
 'Healthcare',
 'Technology',
 'Healthcare',
 'Food & Beverage',
 'Energy',
 'Real Estate',
 'Real Estate',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Fashion & Retail',
 'Technology',
 'Media & Entertainment',
 'Construction & Engineering',
 'Service',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Real Estate',
 'Technology',
 'Diversified',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Manufacturing',
 'Technology',
 'Finance & Investments',
 'Service',
 'Service',
 'Healthcare',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Food & Beverage',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Telecom',
 'Service',
 'Technology',
 'Diversified',
 'Diversified',
 'Automotive',
 'Energy',
 'Finance & Investments',
 'Finance & Investments',
 'Gambling & Casinos',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Food & Beverage',
 'Fashion & Retail',
 'Fashion & Retail',
 'Energy',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Manufacturing',
 'Finance & Investments',
 'Technology',
 'Service',
 'Food & Beverage',
 'Technology',
 'Technology',
 'Manufacturing',
 'Fashion & Retail',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Technology',
 'Finance & Investments',
 'Real Estate',
 'Finance & Investments',
 'Technology',
 'Construction & Engineering',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Fashion & Retail',
 'Healthcare',
 'Food & Beverage',
 'Real Estate',
 'Food & Beverage',
 'Manufacturing',
 'Construction & Engineering',
 'Media & Entertainment',
 'Fashion & Retail',
 'Manufacturing',
 'Diversified',
 'Finance & Investments',
 'Media & Entertainment',
 'Fashion & Retail',
 'Technology',
 'Diversified',
 'Construction & Engineering',
 'Construction & Engineering',
 'Real Estate',
 'Manufacturing',
 'Finance & Investments',
 'Food & Beverage',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Finance & Investments',
 'Telecom',
 'Technology',
 'Service',
 'Technology',
 'Diversified',
 'Finance & Investments',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Metals & Mining',
 'Diversified',
 'Technology',
 'Food & Beverage',
 'Food & Beverage',
 'Diversified',
 'Healthcare',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Real Estate',
 'Construction & Engineering',
 'Manufacturing',
 'Food & Beverage',
 'Healthcare',
 'Fashion & Retail',
 'Media & Entertainment',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Healthcare',
 'Real Estate',
 'Technology',
 'Healthcare',
 'Technology',
 'Healthcare',
 'Food & Beverage',
 'Energy',
 'Real Estate',
 'Real Estate',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Fashion & Retail',
 'Technology',
 'Media & Entertainment',
 'Construction & Engineering',
 'Service',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Real Estate',
 'Technology',
 'Diversified',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Manufacturing',
 'Technology',
 'Finance & Investments',
 'Service',
 'Service',
 'Healthcare',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Food & Beverage',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Telecom',
 'Service',
 'Technology',
 'Diversified',
 'Diversified',
 'Automotive',
 'Energy',
 'Finance & Investments',
 'Finance & Investments',
 'Gambling & Casinos',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Food & Beverage',
 'Fashion & Retail',
 'Fashion & Retail',
 'Energy',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Manufacturing',
 'Finance & Investments',
 'Technology',
 'Service',
 'Food & Beverage',
 'Technology',
 'Technology',
 'Manufacturing',
 'Fashion & Retail',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Technology',
 'Finance & Investments',
 'Real Estate',
 'Finance & Investments',
 'Technology',
 'Construction & Engineering',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Fashion & Retail',
 'Healthcare',
 'Food & Beverage',
 'Real Estate',
 'Food & Beverage',
 'Manufacturing',
 'Construction & Engineering',
 'Media & Entertainment',
 'Fashion & Retail',
 'Manufacturing',
 'Diversified',
 'Finance & Investments',
 'Media & Entertainment',
 'Fashion & Retail',
 'Technology',
 'Diversified',
 'Construction & Engineering',
 'Construction & Engineering',
 'Real Estate',
 'Manufacturing',
 'Finance & Investments',
 'Food & Beverage',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Finance & Investments',
 'Telecom',
 'Technology',
 'Service',
 'Technology',
 'Diversified',
 'Finance & Investments',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Metals & Mining',
 'Diversified',
 'Technology',
 'Food & Beverage',
 'Food & Beverage',
 'Diversified',
 'Healthcare',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Real Estate',
 'Construction & Engineering',
 'Manufacturing',
 'Food & Beverage',
 'Healthcare',
 'Fashion & Retail',
 'Media & Entertainment',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Healthcare',
 'Real Estate',
 'Technology',
 'Healthcare',
 'Technology',
 'Healthcare',
 'Food & Beverage',
 'Energy',
 'Real Estate',
 'Real Estate',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Fashion & Retail',
 'Technology',
 'Media & Entertainment',
 'Construction & Engineering',
 'Service',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Real Estate',
 'Technology',
 'Diversified',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Manufacturing',
 'Technology',
 'Finance & Investments',
 'Service',
 'Service',
 'Healthcare',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Food & Beverage',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Telecom',
 'Service',
 'Technology',
 'Diversified',
 'Diversified',
 'Automotive',
 'Energy',
 'Finance & Investments',
 'Finance & Investments',
 'Gambling & Casinos',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Food & Beverage',
 'Fashion & Retail',
 'Fashion & Retail',
 'Energy',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Manufacturing',
 'Finance & Investments',
 'Technology',
 'Service',
 'Food & Beverage',
 'Technology',
 'Technology',
 'Manufacturing',
 'Fashion & Retail',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Technology',
 'Finance & Investments',
 'Real Estate',
 'Finance & Investments',
 'Technology',
 'Construction & Engineering',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Fashion & Retail',
 'Healthcare',
 'Food & Beverage',
 'Real Estate',
 'Food & Beverage',
 'Manufacturing',
 'Construction & Engineering',
 'Media & Entertainment',
 'Fashion & Retail',
 'Manufacturing',
 'Diversified',
 'Finance & Investments',
 'Media & Entertainment',
 'Fashion & Retail',
 'Technology',
 'Diversified',
 'Construction & Engineering',
 'Construction & Engineering',
 'Real Estate',
 'Manufacturing',
 'Finance & Investments',
 'Food & Beverage',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Finance & Investments',
 'Telecom',
 'Technology',
 'Service',
 'Technology',
 'Diversified',
 'Finance & Investments',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Metals & Mining',
 'Diversified',
 'Technology',
 'Food & Beverage',
 'Food & Beverage',
 'Diversified',
 'Healthcare',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Real Estate',
 'Construction & Engineering',
 'Manufacturing',
 'Food & Beverage',
 'Healthcare',
 'Fashion & Retail',
 'Media & Entertainment',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Healthcare',
 'Real Estate',
 'Technology',
 'Healthcare',
 'Technology',
 'Healthcare',
 'Food & Beverage',
 'Energy',
 'Real Estate',
 'Real Estate',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Fashion & Retail',
 'Technology',
 'Media & Entertainment',
 'Construction & Engineering',
 'Service',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Real Estate',
 'Technology',
 'Diversified',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Manufacturing',
 'Technology',
 'Finance & Investments',
 'Service',
 'Service',
 'Healthcare',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Food & Beverage',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Telecom',
 'Service',
 'Technology',
 'Diversified',
 'Diversified',
 'Automotive',
 'Energy',
 'Finance & Investments',
 'Finance & Investments',
 'Gambling & Casinos',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Food & Beverage',
 'Fashion & Retail',
 'Fashion & Retail',
 'Energy',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Manufacturing',
 'Finance & Investments',
 'Technology',
 'Service',
 'Food & Beverage',
 'Technology',
 'Technology',
 'Manufacturing',
 'Fashion & Retail',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Technology',
 'Finance & Investments',
 'Real Estate',
 'Finance & Investments',
 'Technology',
 'Construction & Engineering',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Fashion & Retail',
 'Healthcare',
 'Food & Beverage',
 'Real Estate',
 'Food & Beverage',
 'Manufacturing',
 'Construction & Engineering',
 'Media & Entertainment',
 'Fashion & Retail',
 'Manufacturing',
 'Diversified',
 'Finance & Investments',
 'Media & Entertainment',
 'Fashion & Retail',
 'Technology',
 'Diversified',
 'Construction & Engineering',
 'Construction & Engineering',
 'Real Estate',
 'Manufacturing',
 'Finance & Investments',
 'Food & Beverage',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Finance & Investments',
 'Telecom',
 'Technology',
 'Service',
 'Technology',
 'Diversified',
 'Finance & Investments',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Metals & Mining',
 'Diversified',
 'Technology',
 'Food & Beverage',
 'Food & Beverage',
 'Diversified',
 'Healthcare',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Real Estate',
 'Construction & Engineering',
 'Manufacturing',
 'Food & Beverage',
 'Healthcare',
 'Fashion & Retail',
 'Media & Entertainment',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Healthcare',
 'Real Estate',
 'Technology',
 'Healthcare',
 'Technology',
 'Healthcare',
 'Food & Beverage',
 'Energy',
 'Real Estate',
 'Real Estate',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Fashion & Retail',
 'Technology',
 'Media & Entertainment',
 'Construction & Engineering',
 'Service',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Real Estate',
 'Technology',
 'Diversified',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Manufacturing',
 'Technology',
 'Finance & Investments',
 'Service',
 'Service',
 'Healthcare',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Food & Beverage',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Telecom',
 'Service',
 'Technology',
 'Diversified',
 'Diversified',
 'Automotive',
 'Energy',
 'Finance & Investments',
 'Finance & Investments',
 'Gambling & Casinos',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Food & Beverage',
 'Fashion & Retail',
 'Fashion & Retail',
 'Energy',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Manufacturing',
 'Finance & Investments',
 'Technology',
 'Service',
 'Food & Beverage',
 'Technology',
 'Technology',
 'Manufacturing',
 'Fashion & Retail',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Technology',
 'Finance & Investments',
 'Real Estate',
 'Finance & Investments',
 'Technology',
 'Construction & Engineering',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Fashion & Retail',
 'Healthcare',
 'Food & Beverage',
 'Real Estate',
 'Food & Beverage',
 'Manufacturing',
 'Construction & Engineering',
 'Media & Entertainment',
 'Fashion & Retail',
 'Manufacturing',
 'Diversified',
 'Finance & Investments',
 'Media & Entertainment',
 'Fashion & Retail',
 'Technology',
 'Diversified',
 'Construction & Engineering',
 'Construction & Engineering',
 'Real Estate',
 'Manufacturing',
 'Finance & Investments',
 'Food & Beverage',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Finance & Investments',
 'Telecom',
 'Technology',
 'Service',
 'Technology',
 'Diversified',
 'Finance & Investments',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Metals & Mining',
 'Diversified',
 'Technology',
 'Food & Beverage',
 'Food & Beverage',
 'Diversified',
 'Healthcare',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Real Estate',
 'Construction & Engineering',
 'Manufacturing',
 'Food & Beverage',
 'Healthcare',
 'Fashion & Retail',
 'Media & Entertainment',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Healthcare',
 'Real Estate',
 'Technology',
 'Healthcare',
 'Technology',
 'Healthcare',
 'Food & Beverage',
 'Energy',
 'Real Estate',
 'Real Estate',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Fashion & Retail',
 'Technology',
 'Media & Entertainment',
 'Construction & Engineering',
 'Service',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Real Estate',
 'Technology',
 'Diversified',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Manufacturing',
 'Technology',
 'Finance & Investments',
 'Service',
 'Service',
 'Healthcare',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Food & Beverage',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Telecom',
 'Service',
 'Technology',
 'Diversified',
 'Diversified',
 'Automotive',
 'Energy',
 'Finance & Investments',
 'Finance & Investments',
 'Gambling & Casinos',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Food & Beverage',
 'Fashion & Retail',
 'Fashion & Retail',
 'Energy',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Manufacturing',
 'Finance & Investments',
 'Technology',
 'Service',
 'Food & Beverage',
 'Technology',
 'Technology',
 'Manufacturing',
 'Fashion & Retail',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Technology',
 'Finance & Investments',
 'Real Estate',
 'Finance & Investments',
 'Technology',
 'Construction & Engineering',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Fashion & Retail',
 'Healthcare',
 'Food & Beverage',
 'Real Estate',
 'Food & Beverage',
 'Manufacturing',
 'Construction & Engineering',
 'Media & Entertainment',
 'Fashion & Retail',
 'Manufacturing',
 'Diversified',
 'Finance & Investments',
 'Media & Entertainment',
 'Fashion & Retail',
 'Technology',
 'Diversified',
 'Construction & Engineering',
 'Construction & Engineering',
 'Real Estate',
 'Manufacturing',
 'Finance & Investments',
 'Food & Beverage',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Finance & Investments',
 'Telecom',
 'Technology',
 'Service',
 'Technology',
 'Diversified',
 'Finance & Investments',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Healthcare',
 'Technology',
 'Manufacturing',
 'Metals & Mining',
 'Diversified',
 'Technology',
 'Food & Beverage',
 'Food & Beverage',
 'Diversified',
 'Healthcare',
 'Finance & Investments',
 'Food & Beverage',
 'Manufacturing',
 'Technology',
 'Fashion & Retail',
 'Diversified',
 'Real Estate',
 'Construction & Engineering',
 'Manufacturing',
 'Food & Beverage',
 'Healthcare',
 'Fashion & Retail',
 'Media & Entertainment',
 'Technology',
 'Food & Beverage',
 'Healthcare',
 'Healthcare',
 'Real Estate',
 'Technology',
 'Healthcare',
 'Technology',
 'Healthcare',
 'Food & Beverage',
 'Energy',
 'Real Estate',
 'Real Estate',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Fashion & Retail',
 'Technology',
 'Media & Entertainment',
 'Construction & Engineering',
 'Service',
 'Finance & Investments',
 'Manufacturing',
 'Manufacturing',
 'Real Estate',
 'Technology',
 'Diversified',
 'Technology',
 'Manufacturing',
 'Food & Beverage',
 'Service',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Manufacturing',
 'Technology',
 'Finance & Investments',
 'Service',
 'Service',
 'Healthcare',
 'Technology',
 'Media & Entertainment',
 'Manufacturing',
 'Energy',
 'Diversified',
 'Real Estate',
 'Food & Beverage',
 'Fashion & Retail',
 'Service',
 'Technology',
 'Telecom',
 'Service',
 ...]

In [34]:
Nos=[]
for i in range(1,len(Industrys)+1):
    Nos.append(i)
Nos

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 210,
 211,
 212,
 213,
 214,
 215,
 216,
 217,
 218,
 219,
 220,
 221,
 222,
 223,
 224,
 225,
 226,
 227,
 228,
 229,
 230,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 471,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 485,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 494,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 505,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 ...]

In [39]:
import pandas as pd
Billionaires=pd.DataFrame({})
Billionaires['Nos']=Nos[:2015]
Billionaires['Rank']=rank1[:2015]
Billionaires['Names']=names[:2015]
Billionaires['Net worth']=net_worths[:2015]
Billionaires['Age']=Ages[:2015]
Billionaires['Country']=citizens[:2015]
Billionaires['Source']=sources[:2015]
Billionaires['Industry']=Industrys[:2015]
Billionaires.style.hide_index()

These are the Billionaires records from forbes website

In [41]:
Billionaires.to_csv('Billionaires.csv')